// ── Types ──────────────────────────────────────────────────────────────────────
export type Difficulty = 1 | 2 | 3;
export type BilingualText = string | { ko: string; en: string };

export interface DifficultyQ {
  id: string | number;
  q: BilingualText;
  answer: boolean;
  explain: BilingualText;
  tag: BilingualText;
  difficulty: Difficulty;
}

// ── Level → Difficulty mapping ─────────────────────────────────────────────────
// Levels 1-4  → difficulty 1 (입문)
// Levels 5-7  → difficulty 2 (중급)
// Levels 8-10 → difficulty 3 (고급)
export function getDifficultyForLevel(level: number): Difficulty {
  if (level <= 4) return 1;
  if (level <= 7) return 2;
  return 3;
}

// ── Helpers ───────────────────────────────────────────────────────────────────
export function getQuizByDifficulty(difficulty: Difficulty): DifficultyQ[] {
  return QUIZ_POOL.filter((q) => q.difficulty === difficulty);
}

export function pickRandom(pool: DifficultyQ[], count: number): DifficultyQ[] {
  const arr = [...pool];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr.slice(0, count);
}

/** 레벨을 받아 해당 난이도의 풀에서 count개 랜덤 추출 */
export function pickByLevel(level: number, count: number): DifficultyQ[] {
  return pickRandom(getQuizByDifficulty(getDifficultyForLevel(level)), count);
}

/** 언어 코드에 맞는 텍스트 반환 (plain string은 그대로 반환) */
export function getText(field: BilingualText, lang: string): string {
  if (typeof field === "string") return field;
  return lang === "ko" ? field.ko : field.en;
}

// ── Quiz pool ─────────────────────────────────────────────────────────────────
export const QUIZ_POOL: DifficultyQ[] = [

  // ════════════════════════════════════════════════
  //  DIFFICULTY 1 — 입문 (Lv 1-4)
  // ════════════════════════════════════════════════

  {
    id: 101,
    difficulty: 1,
    tag: { ko: "🏢 기업 상식", en: "🏢 Company Facts" },
    q: { ko: "테슬라(Tesla)는 전기차를 만드는 회사다", en: "Tesla is a company that makes electric vehicles" },
    answer: true,
    explain: { ko: "맞아요! 테슬라는 전기차 외에도 에너지 저장(Powerwall), 태양광 패널, 자율주행(FSD)도 판매해요 ⚡", en: "Correct! Tesla also sells energy storage (Powerwall), solar panels, and autonomous driving (FSD) ⚡" },
  },
  {
    id: 102,
    difficulty: 1,
    tag: { ko: "🏢 기업 상식", en: "🏢 Company Facts" },
    q: { ko: "애플(Apple)의 현재 CEO는 팀 쿡(Tim Cook)이다", en: "Tim Cook is Apple's current CEO" },
    answer: true,
    explain: { ko: "스티브 잡스 타계 후 2011년부터 팀 쿡이 CEO를 맡고 있어요 🍎", en: "Tim Cook has served as Apple's CEO since 2011, following Steve Jobs' passing 🍎" },
  },
  {
    id: 103,
    difficulty: 1,
    tag: { ko: "🏢 기업 상식", en: "🏢 Company Facts" },
    q: { ko: "아마존(Amazon)은 처음에 온라인 서점으로 시작했다", en: "Amazon started as an online bookstore" },
    answer: true,
    explain: { ko: "1994년 제프 베이조스가 책 판매 온라인몰로 창업했어요. 지금은 클라우드·물류 제국이 됐죠 📦", en: "Jeff Bezos founded it as an online book retailer in 1994. It's now a cloud and logistics empire 📦" },
  },
  {
    id: 104,
    difficulty: 1,
    tag: { ko: "🏢 기업 상식", en: "🏢 Company Facts" },
    q: { ko: "유튜브는 넷플릭스가 인수한 서비스다", en: "YouTube was acquired by Netflix" },
    answer: false,
    explain: { ko: "유튜브는 2006년 구글(현 알파벳)이 16.5억 달러에 인수했어요. 넷플릭스와는 관계 없어요 🎥", en: "YouTube was acquired by Google (now Alphabet) for $1.65 billion in 2006. Netflix had nothing to do with it 🎥" },
  },
  {
    id: 105,
    difficulty: 1,
    tag: { ko: "🏢 기업 상식", en: "🏢 Company Facts" },
    q: { ko: "인스타그램은 메타(Meta)가 소유하고 있다", en: "Instagram is owned by Meta" },
    answer: true,
    explain: { ko: "2012년 페이스북(현 메타)이 10억 달러에 인수했어요 📸", en: "Facebook (now Meta) acquired it for $1 billion in 2012 📸" },
  },
  {
    id: 106,
    difficulty: 1,
    tag: { ko: "🏢 기업 상식", en: "🏢 Company Facts" },
    q: { ko: "넷플릭스는 처음부터 영상 스트리밍 서비스로 시작했다", en: "Netflix started as a video streaming service from the beginning" },
    answer: false,
    explain: { ko: "1997년 DVD 우편 대여 서비스로 시작해 2007년 스트리밍으로 전환했어요 📀", en: "It started as a DVD mail rental service in 1997 and transitioned to streaming in 2007 📀" },
  },
  {
    id: 107,
    difficulty: 1,
    tag: { ko: "🏢 기업 상식", en: "🏢 Company Facts" },
    q: { ko: "구글의 모회사 이름은 알파벳(Alphabet)이다", en: "Google's parent company is called Alphabet" },
    answer: true,
    explain: { ko: "2015년 지주회사 알파벳을 설립했어요. 구글, 유튜브, 딥마인드 등이 자회사예요 🔍", en: "Alphabet was established as a holding company in 2015. Google, YouTube, and DeepMind are among its subsidiaries 🔍" },
  },
  {
    id: 108,
    difficulty: 1,
    tag: { ko: "🏢 기업 상식", en: "🏢 Company Facts" },
    q: { ko: "마이크로소프트는 Xbox 게임기를 만든다", en: "Microsoft makes the Xbox gaming console" },
    answer: true,
    explain: { ko: "Xbox 브랜드로 콘솔과 Game Pass 구독 서비스를 운영 중이에요 🎮", en: "Microsoft operates the Xbox console and Game Pass subscription service under the Xbox brand 🎮" },
  },
  {
    id: 109,
    difficulty: 1,
    tag: { ko: "🏢 기업 상식", en: "🏢 Company Facts" },
    q: { ko: "삼성전자는 미국 나스닥에 상장되어 있다", en: "Samsung Electronics is listed on the US NASDAQ" },
    answer: false,
    explain: { ko: "삼성전자는 한국 코스피(KRX)에 상장되어 있어요. 미국에는 ADR 형태로 OTC 거래는 돼요 🇰🇷", en: "Samsung Electronics is listed on the Korean KOSPI (KRX). It trades in the US only as an OTC ADR 🇰🇷" },
  },
  {
    id: 110,
    difficulty: 1,
    tag: { ko: "🏢 기업 상식", en: "🏢 Company Facts" },
    q: { ko: "비트코인은 특정 국가의 중앙은행이 발행한다", en: "Bitcoin is issued by a specific country's central bank" },
    answer: false,
    explain: { ko: "비트코인은 탈중앙화 네트워크에서 채굴자들이 생성해요. 어떤 정부도 통제하지 않아요 ₿", en: "Bitcoin is created by miners on a decentralized network. No government controls it ₿" },
  },
  {
    id: 111,
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "주식을 1주만 사도 그 회사의 주주가 된다", en: "Buying even 1 share makes you a shareholder of that company" },
    answer: true,
    explain: { ko: "1주라도 보유하면 공식 주주! 주주총회 참여권과 배당받을 권리가 생겨요 📜", en: "Holding even one share makes you an official shareholder with voting rights and the right to receive dividends 📜" },
  },
  {
    id: 112,
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "주식에 투자하면 원금이 보장된다", en: "Investing in stocks guarantees your principal" },
    answer: false,
    explain: { ko: "주식은 원금 비보장 상품이에요. 회사 주가가 떨어지면 원금 손실이 날 수 있어요 ⚠️", en: "Stocks do not guarantee your principal. If the stock price falls, you can lose part or all of your investment ⚠️" },
  },
  {
    id: 113,
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "ETF는 주식처럼 장중 실시간으로 매매할 수 있다", en: "ETFs can be traded in real time during market hours, just like stocks" },
    answer: true,
    explain: { ko: "ETF(Exchange-Traded Fund)는 거래소에서 주식처럼 자유롭게 사고팔 수 있어요 📊", en: "ETFs (Exchange-Traded Funds) can be freely bought and sold on an exchange just like stocks 📊" },
  },
  {
    id: 114,
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "나스닥(NASDAQ)은 기술주 중심의 미국 주식 거래소다", en: "NASDAQ is a US stock exchange focused on technology stocks" },
    answer: true,
    explain: { ko: "애플, 구글, 아마존 등 대형 기술주가 주로 나스닥에 상장되어 있어요 💻", en: "Major tech stocks like Apple, Google, and Amazon are primarily listed on NASDAQ 💻" },
  },
  {
    id: 115,
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "미국 주식 시장(NYSE)은 월요일부터 금요일까지만 운영된다", en: "The US stock market (NYSE) operates only Monday through Friday" },
    answer: true,
    explain: { ko: "미 동부시간 기준 평일 오전 9:30 ~ 오후 4:00 운영이에요. 주말·공휴일은 쉬어요 🕒", en: "The market runs weekdays 9:30 AM – 4:00 PM Eastern Time. It's closed on weekends and holidays 🕒" },
  },
  {
    id: 116,
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "배당금을 받으려면 최소 100주 이상 보유해야 한다", en: "You need to hold at least 100 shares to receive a dividend" },
    answer: false,
    explain: { ko: "1주만 있어도 배당 기준일에 보유하고 있으면 배당금을 받을 수 있어요 💵", en: "Even 1 share qualifies you for dividends as long as you hold it on the record date 💵" },
  },
  {
    id: 117,
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "S&P500은 미국 대형주 500개로 구성된 주가지수다", en: "The S&P 500 is a stock index composed of 500 large US companies" },
    answer: true,
    explain: { ko: "1957년 시작, 미국 전체 주식시장 시가총액의 80% 이상을 반영하는 대표 지수예요 📈", en: "Started in 1957, it represents over 80% of the total US stock market capitalization 📈" },
  },
  {
    id: 118,
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "금(Gold)에 투자하면 정기적으로 배당금을 받을 수 있다", en: "Investing in gold gives you regular dividend payments" },
    answer: false,
    explain: { ko: "금은 실물 자산으로 배당이나 이자가 없어요. 가격 상승으로만 수익을 낼 수 있어요 🥇", en: "Gold is a physical asset that pays no dividends or interest. Profits come only from price appreciation 🥇" },
  },
  {
    id: 119,
    difficulty: 1,
    tag: { ko: "🤖 테크 & AI", en: "🤖 Tech & AI" },
    q: { ko: "NVIDIA는 원래 게임용 그래픽카드(GPU)를 만드는 회사였다", en: "NVIDIA originally made gaming graphics cards (GPUs)" },
    answer: true,
    explain: { ko: "1993년 게이밍 GPU로 시작해 AI 시대에 데이터센터 칩 1위로 변신했어요 🎮", en: "Founded in 1993 as a gaming GPU company, it transformed into the top data center chip maker in the AI era 🎮" },
  },
  {
    id: 120,
    difficulty: 1,
    tag: { ko: "🤖 테크 & AI", en: "🤖 Tech & AI" },
    q: { ko: "오픈AI(OpenAI)를 처음 설립한 사람은 마이크로소프트다", en: "Microsoft was the original founder of OpenAI" },
    answer: false,
    explain: { ko: "2015년 샘 알트만, 일론 머스크 등이 공동 창업했어요. 마이크로소프트는 나중에 투자했어요 🤖", en: "Sam Altman, Elon Musk, and others co-founded it in 2015. Microsoft invested later 🤖" },
  },
  {
    id: 121,
    difficulty: 1,
    tag: { ko: "💡 투자 개념", en: "💡 Investment Concepts" },
    q: { ko: "워런 버핏은 단기 트레이딩을 선호하는 투자자다", en: "Warren Buffett is an investor who prefers short-term trading" },
    answer: false,
    explain: { ko: "'10년 보유할 생각 없으면 10분도 보유하지 마라'는 장기투자의 대가예요 🐘", en: "'If you aren't willing to own a stock for 10 years, don't even think about owning it for 10 minutes' — the master of long-term investing 🐘" },
  },
  {
    id: 122,
    difficulty: 1,
    tag: { ko: "💡 투자 개념", en: "💡 Investment Concepts" },
    q: { ko: "분산 투자는 한 종목에 몰빵하는 것보다 리스크를 줄여준다", en: "Diversified investing reduces risk compared to putting everything in one stock" },
    answer: true,
    explain: { ko: "여러 자산에 나눠 투자하면 하나가 떨어져도 전체 손실 폭이 줄어들어요 📊", en: "Spreading investments across multiple assets limits your overall losses if any single one falls 📊" },
  },

  // ── 주식 기초 q001-q025 ───────────────────────
  {
    id: "q001",
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "주식(Stock)은 기업이 자금 조달을 위해 발행하는 소유권 증서다", en: "A stock is an ownership certificate issued by a company to raise funds" },
    answer: true,
    explain: { ko: "주식을 사면 그 기업의 일부를 소유하는 주주가 돼요. 기업은 주식을 팔아 사업 자금을 마련해요 📜", en: "Buying a stock makes you a partial owner (shareholder). Companies sell shares to raise business capital 📜" },
  },
  {
    id: "q002",
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "주식을 구매하면 그 기업의 채권자(돈을 빌려준 사람)가 된다", en: "Buying stock in a company makes you a creditor (someone who lent money)" },
    answer: false,
    explain: { ko: "주식을 사면 주주(소유자)가 돼요. 돈을 빌려주는 사람은 채권자이고, 그건 채권 투자예요 📄", en: "Buying stock makes you a shareholder (owner), not a creditor. Lending money is what bond investors do 📄" },
  },
  {
    id: "q003",
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "주가가 오르면 주식을 보유한 투자자의 평가 이익이 늘어난다", en: "When a stock price rises, the paper gains of shareholders increase" },
    answer: true,
    explain: { ko: "사둔 주식의 가격이 올라가면 팔았을 때 그 차액만큼 이익이 생겨요 📈", en: "If the price of a stock you own goes up, you earn the difference when you sell 📈" },
  },
  {
    id: "q004",
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "미국 주식은 일부 증권사에서 소수점 단위로도 구매할 수 있다", en: "US stocks can be purchased in fractional shares at some brokerages" },
    answer: true,
    explain: { ko: "애플 1주가 200달러라도 0.5주(100달러)어치 살 수 있는 소수점 매매 서비스가 있어요 🍎", en: "Even if 1 Apple share costs $200, you can buy 0.5 shares ($100) through fractional share services 🍎" },
  },
  {
    id: "q005",
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "다우존스 산업평균지수(DJIA)는 미국 대표 기업 30개로 구성된다", en: "The Dow Jones Industrial Average (DJIA) is made up of 30 major US companies" },
    answer: true,
    explain: { ko: "1896년에 만들어진 미국에서 가장 오래된 주가지수예요. 애플, 맥도날드, JP모건 등이 포함돼요 📊", en: "Created in 1896, it's America's oldest stock index. It includes Apple, McDonald's, JPMorgan, and more 📊" },
  },
  {
    id: "q006",
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "뉴욕증권거래소(NYSE)는 상장 기업 시가총액 기준 세계 최대 규모의 증권거래소다", en: "The New York Stock Exchange (NYSE) is the world's largest stock exchange by listed company market cap" },
    answer: true,
    explain: { ko: "월스트리트에 자리한 NYSE는 시가총액 기준 세계 1위 거래소예요 🗽", en: "Located on Wall Street, the NYSE is the world's largest exchange by market capitalization 🗽" },
  },
  {
    id: "q007",
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "주식의 액면가(Par Value)와 시장에서 실제 거래되는 가격은 항상 같다", en: "A stock's par value and its actual market trading price are always the same" },
    answer: false,
    explain: { ko: "액면가는 설정된 명목상 가격일 뿐, 실제 주가는 수요와 공급에 따라 달라져요 💹", en: "Par value is just a nominal price set at issuance. The actual market price fluctuates with supply and demand 💹" },
  },
  {
    id: "q008",
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "IPO(기업공개)란 기업이 처음으로 일반 대중에게 주식을 판매하는 것이다", en: "An IPO (Initial Public Offering) is when a company first sells shares to the general public" },
    answer: true,
    explain: { ko: "Initial Public Offering. 비상장 기업이 증권거래소에 처음 상장될 때 진행하는 절차예요 🎉", en: "Initial Public Offering — the process by which a private company first lists on a stock exchange 🎉" },
  },
  {
    id: "q009",
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "주식 시장에서 '강세장(Bull Market)'은 주가가 장기적으로 하락하는 장을 말한다", en: "A 'bull market' refers to a prolonged period of falling stock prices" },
    answer: false,
    explain: { ko: "Bull(황소)은 뿔로 위를 받아 올려요. 강세장은 주가가 장기적으로 오르는 상승장이에요 🐂", en: "A bull thrusts its horns upward. A bull market is when stock prices rise over an extended period 🐂" },
  },
  {
    id: "q010",
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "주식 시장에서 '약세장(Bear Market)'은 주가가 고점 대비 20% 이상 하락한 장을 말한다", en: "A 'bear market' refers to a decline of 20% or more from the market's peak" },
    answer: true,
    explain: { ko: "Bear(곰)은 앞발로 아래를 후려쳐요. 고점 대비 20%+ 하락한 장을 약세장이라 해요 🐻", en: "A bear swipes its paws downward. A bear market is defined as a 20%+ drop from a peak 🐻" },
  },
  {
    id: "q011",
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "미국 주식은 정규장 외에 개장 전(Pre-market)과 마감 후(After-hours)에도 거래할 수 있다", en: "US stocks can also be traded before the market opens (pre-market) and after it closes (after-hours)" },
    answer: true,
    explain: { ko: "다만 유동성이 낮아 정규장보다 불리한 조건으로 거래될 수 있으니 주의해요 ⏰", en: "However, liquidity is lower, so you may trade at less favorable prices than during regular hours ⏰" },
  },
  {
    id: "q012",
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "주식을 팔아 이익을 냈다면 양도소득세가 발생할 수 있다", en: "If you profit from selling stocks, capital gains tax may apply" },
    answer: true,
    explain: { ko: "한국 거주자의 미국 주식 매매 차익은 22%(지방세 포함) 양도소득세 과세 대상이에요 💸", en: "For Korean residents, profits from US stock sales are subject to a 22% capital gains tax (including local tax) 💸" },
  },
  {
    id: "q013",
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "주식의 시장 가격은 정부가 정하는 것이 아니라 매수·매도자 간 수요·공급으로 결정된다", en: "Stock market prices are determined by supply and demand between buyers and sellers, not by the government" },
    answer: true,
    explain: { ko: "경매처럼 사려는 사람(수요)과 팔려는 사람(공급)이 합의하는 가격이 주가예요 🔄", en: "Like an auction, the stock price is where a buyer (demand) and seller (supply) agree to transact 🔄" },
  },
  {
    id: "q014",
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "주식을 보유하면 은행 예금처럼 매년 이자가 자동으로 붙는다", en: "Holding stocks automatically earns you interest each year, like a bank deposit" },
    answer: false,
    explain: { ko: "주식에는 이자가 없어요. 수익은 주가 상승과 배당금으로만 생겨요 💡", en: "Stocks do not pay interest. Returns come only from price appreciation and dividends 💡" },
  },
  {
    id: "q015",
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "기업이 파산할 경우 주주는 채권자보다 회사 자산을 먼저 돌려받는다", en: "If a company goes bankrupt, shareholders are paid back before creditors" },
    answer: false,
    explain: { ko: "파산 시 채권자, 세금, 임금 등을 먼저 갚고 남은 것이 있을 때만 주주에게 돌아가요 ⚠️", en: "In bankruptcy, creditors, taxes, and wages are paid first. Shareholders only get what's left over, if anything ⚠️" },
  },
  {
    id: "q016",
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "주식 투자는 은행 예금과 달리 원금이 보장되지 않는다", en: "Unlike bank deposits, stock investments do not guarantee your principal" },
    answer: true,
    explain: { ko: "주가가 0이 되면 원금 전부를 잃을 수도 있어요. 높은 수익 가능성 뒤에는 위험이 따라요 💸", en: "If a stock price hits zero, you lose your entire investment. Higher return potential always comes with higher risk 💸" },
  },
  {
    id: "q017",
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "주식을 사려면 반드시 증권사에 계좌를 개설해야 한다", en: "You must open a brokerage account to buy stocks" },
    answer: true,
    explain: { ko: "증권계좌 없이는 주식 거래를 할 수 없어요. 요즘은 앱으로 비대면 개설이 가능해요 📱", en: "You cannot trade stocks without a brokerage account. These days you can open one online via an app 📱" },
  },
  {
    id: "q018",
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "시가(Open Price)는 해당 날 주식 거래가 처음 시작될 때의 가격이다", en: "The opening price is the price at which trading first begins for the day" },
    answer: true,
    explain: { ko: "장이 열리는 첫 체결 거래에서 결정되는 가격이에요. 전날 종가와 다를 수 있어요 🌅", en: "It's determined by the first transaction of the trading day. It can differ from the previous day's closing price 🌅" },
  },
  {
    id: "q019",
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "종가(Close Price)는 해당 날 가장 마지막에 체결된 거래 가격이다", en: "The closing price is the price of the last trade executed that day" },
    answer: true,
    explain: { ko: "당일 최종 주가이며, 다음 날 거래의 기준점이 돼요 🌆", en: "It is the final price of the day and serves as the reference point for the next trading day 🌆" },
  },
  {
    id: "q020",
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "거래량이 많다는 것은 해당 주식의 매수·매도 거래가 활발하다는 의미다", en: "High trading volume means buying and selling of that stock is very active" },
    answer: true,
    explain: { ko: "거래량이 많을수록 유동성이 높아 원하는 가격에 쉽게 사고팔 수 있어요 📊", en: "The higher the volume, the more liquid the stock, making it easier to buy and sell at your desired price 📊" },
  },
  {
    id: "q021",
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "주식 분할(Stock Split) 시 주주가 보유한 주식 수는 늘어난다", en: "In a stock split, the number of shares a shareholder holds increases" },
    answer: true,
    explain: { ko: "1:4 분할이면 100주 보유자가 400주를 갖게 돼요. 주가는 1/4이 되어 시총은 동일해요 📊", en: "In a 4-for-1 split, 100 shares become 400. The price drops to 1/4, so total market cap stays the same 📊" },
  },
  {
    id: "q022",
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "'52주 최고가'란 최근 1년 중 해당 주식이 거래된 가장 높은 가격이다", en: "The '52-week high' is the highest price at which a stock has traded in the past year" },
    answer: true,
    explain: { ko: "52주 신고가 돌파는 강한 상승 모멘텀의 신호로 해석되기도 해요 📈", en: "Breaking a 52-week high is often seen as a signal of strong upward momentum 📈" },
  },
  {
    id: "q023",
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "미국의 S&P500, 나스닥 종합, 다우존스 지수는 모두 동일한 종목을 추종하는 같은 지수다", en: "The S&P 500, NASDAQ Composite, and Dow Jones are all the same index tracking the same stocks" },
    answer: false,
    explain: { ko: "세 지수는 구성 종목과 산정 방식이 달라요. 각각 미국 시장의 다른 단면을 보여줘요 📊", en: "The three indices differ in their constituents and calculation methods, each showing a different slice of the US market 📊" },
  },
  {
    id: "q024",
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "주식 시장에서 '유동성(Liquidity)'이 높다는 것은 해당 주식을 쉽고 빠르게 사고팔 수 있다는 의미다", en: "High 'liquidity' in the stock market means a stock can be bought and sold easily and quickly" },
    answer: true,
    explain: { ko: "유동성이 낮으면 팔고 싶어도 매수자가 없어 원하는 가격에 팔지 못할 수 있어요 💧", en: "Low liquidity means there may be no buyer when you want to sell, forcing you to accept a worse price 💧" },
  },
  {
    id: "q025",
    difficulty: 1,
    tag: { ko: "📊 주식 기초", en: "📊 Stock Basics" },
    q: { ko: "코스피(KOSPI)는 한국거래소(KRX)에 상장된 종목들로 구성된 한국 대표 주가지수다", en: "KOSPI is South Korea's benchmark stock index, composed of companies listed on the Korea Exchange (KRX)" },
    answer: true,
    explain: { ko: "Korea Composite Stock Price Index. 삼성전자, SK하이닉스 등 대형주가 포함돼요 🇰🇷", en: "Korea Composite Stock Price Index — includes large-cap stocks like Samsung Electronics and SK Hynix 🇰🇷" },
  },

  // ── ETF q026-q050 ─────────────────────────────
  {
    id: "q026",
    difficulty: 1,
    tag: { ko: "📦 ETF", en: "📦 ETF" },
    q: { ko: "ETF는 'Exchange-Traded Fund'의 약자로 한국어로 '상장지수펀드'라고 한다", en: "ETF stands for 'Exchange-Traded Fund'" },
    answer: true,
    explain: { ko: "거래소(Exchange)에 상장(Listed)돼 주식처럼 자유롭게 거래할 수 있는 펀드예요 📊", en: "It's a fund listed on an exchange that can be traded freely like a stock 📊" },
  },
  {
    id: "q027",
    difficulty: 1,
    tag: { ko: "📦 ETF", en: "📦 ETF" },
    q: { ko: "SPY ETF는 S&P500 지수를 추종하는 미국 최초의 ETF다", en: "SPY ETF is the first US ETF tracking the S&P 500 index" },
    answer: true,
    explain: { ko: "SPDR S&P 500 ETF Trust. 1993년에 출시됐으며 운용 자산 규모가 세계 최대 수준이에요 🏆", en: "SPDR S&P 500 ETF Trust, launched in 1993. It is among the largest ETFs in the world by assets 🏆" },
  },
  {
    id: "q028",
    difficulty: 1,
    tag: { ko: "📦 ETF", en: "📦 ETF" },
    q: { ko: "ETF 운용보수(Expense Ratio)가 낮을수록 장기 투자자에게 유리하다", en: "A lower expense ratio is more advantageous for long-term ETF investors" },
    answer: true,
    explain: { ko: "연 0.03% vs 1%의 보수 차이가 30년 복리로 쌓이면 최종 자산에 엄청난 차이를 만들어요 💰", en: "The difference between 0.03% and 1% annual fees compounded over 30 years can make a massive difference in final wealth 💰" },
  },
  {
    id: "q029",
    difficulty: 1,
    tag: { ko: "📦 ETF", en: "📦 ETF" },
    q: { ko: "ETF는 일반 뮤추얼펀드와 달리 주식처럼 장중 실시간 매매가 가능하다", en: "Unlike regular mutual funds, ETFs can be traded in real time during market hours like stocks" },
    answer: true,
    explain: { ko: "뮤추얼펀드는 하루 한 번 종가로 거래하지만, ETF는 정규장 내내 실시간으로 사고팔 수 있어요 ⚡", en: "Mutual funds trade once a day at the closing price, but ETFs can be bought and sold throughout the trading day ⚡" },
  },
  {
    id: "q030",
    difficulty: 1,
    tag: { ko: "📦 ETF", en: "📦 ETF" },
    q: { ko: "QQQ ETF는 나스닥100 지수를 추종하는 대표적인 ETF다", en: "QQQ ETF is a leading ETF that tracks the NASDAQ-100 index" },
    answer: true,
    explain: { ko: "Invesco QQQ Trust. 애플, 마이크로소프트, 엔비디아 등 나스닥 상위 100개 기업에 투자해요 💻", en: "Invesco QQQ Trust — invests in the top 100 NASDAQ companies, including Apple, Microsoft, and NVIDIA 💻" },
  },
  {
    id: "q031",
    difficulty: 1,
    tag: { ko: "📦 ETF", en: "📦 ETF" },
    q: { ko: "VOO ETF는 블랙록(BlackRock)이 운용하는 S&P500 ETF다", en: "VOO ETF is an S&P 500 ETF managed by BlackRock" },
    answer: false,
    explain: { ko: "VOO는 뱅가드(Vanguard)가 운용해요. 블랙록의 S&P500 ETF는 IVV예요 📊", en: "VOO is managed by Vanguard, not BlackRock. BlackRock's S&P 500 ETF is IVV 📊" },
  },
  {
    id: "q032",
    difficulty: 1,
    tag: { ko: "📦 ETF", en: "📦 ETF" },
    q: { ko: "인버스(Inverse) ETF는 기초지수가 하락할 때 이익이 나도록 설계된 상품이다", en: "An inverse ETF is designed to profit when its underlying index falls" },
    answer: true,
    explain: { ko: "SQQQ는 나스닥이 1% 내리면 약 3% 오르는 3배 인버스 ETF예요. 하락에 베팅하는 상품이에요 📉", en: "SQQQ is a 3x inverse ETF that rises ~3% when the NASDAQ falls 1%. It's a way to bet on declines 📉" },
  },
  {
    id: "q033",
    difficulty: 1,
    tag: { ko: "📦 ETF", en: "📦 ETF" },
    q: { ko: "채권 ETF는 여러 채권을 한 바구니에 담아 분산 투자하는 효과를 제공한다", en: "Bond ETFs offer diversified exposure by bundling multiple bonds into one basket" },
    answer: true,
    explain: { ko: "BND, AGG 같은 채권 ETF는 수천 개 채권에 분산 투자해 개별 채권보다 안정적이에요 💼", en: "Bond ETFs like BND and AGG invest in thousands of bonds, making them more stable than holding individual bonds 💼" },
  },
  {
    id: "q034",
    difficulty: 1,
    tag: { ko: "📦 ETF", en: "📦 ETF" },
    q: { ko: "섹터 ETF를 이용하면 반도체, 헬스케어 등 특정 산업에만 집중 투자할 수 있다", en: "Sector ETFs allow you to invest exclusively in specific industries like semiconductors or healthcare" },
    answer: true,
    explain: { ko: "SOXX(반도체), XLV(헬스케어), XLE(에너지) 등 업종별로 다양한 섹터 ETF가 있어요 🏭", en: "There are sector ETFs for many industries, including SOXX (semiconductors), XLV (healthcare), and XLE (energy) 🏭" },
  },
  {
    id: "q035",
    difficulty: 1,
    tag: { ko: "📦 ETF", en: "📦 ETF" },
    q: { ko: "ETF는 반드시 주식으로만 구성되어야 한다", en: "ETFs must consist only of stocks" },
    answer: false,
    explain: { ko: "채권, 금, 원유, 부동산(REITs), 비트코인 등 다양한 자산으로 구성된 ETF도 있어요 💡", en: "ETFs can also hold bonds, gold, oil, real estate (REITs), bitcoin, and many other asset types 💡" },
  },
  {
    id: "q036",
    difficulty: 1,
    tag: { ko: "📦 ETF", en: "📦 ETF" },
    q: { ko: "VTI ETF는 미국 전체 주식시장에 투자하는 ETF다", en: "VTI ETF invests in the entire US stock market" },
    answer: true,
    explain: { ko: "Vanguard Total Stock Market ETF. 소형주까지 포함해 미국 전체 종목에 투자해요 🇺🇸", en: "Vanguard Total Stock Market ETF — invests in the entire US market, including small-cap stocks 🇺🇸" },
  },
  {
    id: "q037",
    difficulty: 1,
    tag: { ko: "📦 ETF", en: "📦 ETF" },
    q: { ko: "ETF를 보유하면 ETF가 담고 있는 종목에서 발생하는 배당금을 받을 수 있다", en: "ETF holders can receive dividends generated by the stocks held within the ETF" },
    answer: true,
    explain: { ko: "ETF 내 종목에서 배당이 발생하면 비중에 따라 ETF 투자자에게도 배당이 분배돼요 💵", en: "When the stocks inside an ETF pay dividends, those are distributed to ETF investors proportionally 💵" },
  },
  {
    id: "q038",
    difficulty: 1,
    tag: { ko: "📦 ETF", en: "📦 ETF" },
    q: { ko: "ETF는 보유 종목을 매일 공개하므로 일반 펀드보다 운용 투명성이 높다", en: "ETFs are more transparent than regular funds because they disclose their holdings daily" },
    answer: true,
    explain: { ko: "대부분의 ETF는 매일 보유 자산을 공시해 투자자가 직접 확인할 수 있어요 🔍", en: "Most ETFs publish their holdings daily, allowing investors to see exactly what they own 🔍" },
  },
  {
    id: "q039",
    difficulty: 1,
    tag: { ko: "📦 ETF", en: "📦 ETF" },
    q: { ko: "GLD ETF는 금(Gold) 가격 변동을 추적하는 대표적인 원자재 ETF다", en: "GLD ETF is a leading commodity ETF that tracks the price of gold" },
    answer: true,
    explain: { ko: "실제 금을 보관하고 그 가치를 ETF 가격에 반영해요. 금에 간접 투자하는 방법이에요 🥇", en: "It holds physical gold and reflects its value in the ETF price — an indirect way to invest in gold 🥇" },
  },
  {
    id: "q040",
    difficulty: 1,
    tag: { ko: "📦 ETF", en: "📦 ETF" },
    q: { ko: "레버리지 ETF(2배·3배)는 기초지수 수익의 2배 또는 3배를 일별로 추구한다", en: "Leveraged ETFs (2x or 3x) aim to deliver 2x or 3x the daily return of their underlying index" },
    answer: true,
    explain: { ko: "'일별 리셋' 구조 때문에 장기 보유 시 지수 배수와 실제 수익이 크게 차이 날 수 있어요 ⚠️", en: "Due to the 'daily reset' structure, long-term returns can differ significantly from the expected multiple ⚠️" },
  },
  {
    id: "q041",
    difficulty: 1,
    tag: { ko: "📦 ETF", en: "📦 ETF" },
    q: { ko: "국내 ETF 상품명에 'TIGER', 'KODEX', 'ARIRANG' 등이 붙는 것은 자산운용사별 브랜드명이다", en: "Names like 'TIGER', 'KODEX', and 'ARIRANG' on Korean ETFs are brand names of asset management companies" },
    answer: true,
    explain: { ko: "TIGER=미래에셋, KODEX=삼성자산운용, ARIRANG=한화자산운용이에요 🏦", en: "TIGER = Mirae Asset, KODEX = Samsung Asset Management, ARIRANG = Hanwha Asset Management 🏦" },
  },
  {
    id: "q042",
    difficulty: 1,
    tag: { ko: "📦 ETF", en: "📦 ETF" },
    q: { ko: "ETF를 거래할 때 증권사에 별도의 거래 수수료가 발생할 수 있다", en: "When trading ETFs, separate brokerage commissions may apply" },
    answer: true,
    explain: { ko: "운용보수와 별도로 매매 시 증권사 수수료가 붙을 수 있어요. 최근엔 무료 서비스도 많아요 💳", en: "Brokerage commissions are separate from the expense ratio. Many brokers now offer commission-free ETF trading 💳" },
  },
  {
    id: "q043",
    difficulty: 1,
    tag: { ko: "📦 ETF", en: "📦 ETF" },
    q: { ko: "해외 ETF에 투자하면 환율 변동에 따라 원화 기준 수익이 달라질 수 있다", en: "Investing in foreign ETFs means your returns in Korean won can vary with exchange rate fluctuations" },
    answer: true,
    explain: { ko: "달러 ETF 수익이 5%여도 원화가 5% 강세이면 원화 기준 수익은 거의 0%가 될 수 있어요 💱", en: "Even a 5% gain in a dollar ETF can be wiped out if the won strengthens 5% against the dollar 💱" },
  },
  {
    id: "q044",
    difficulty: 1,
    tag: { ko: "📦 ETF", en: "📦 ETF" },
    q: { ko: "S&P500 ETF는 500개 종목 모두에 동일한 비율로 투자한다", en: "S&P 500 ETFs invest in all 500 stocks at equal weight" },
    answer: false,
    explain: { ko: "시가총액 가중 방식이에요. 애플, 마이크로소프트 같은 대형주 비중이 훨씬 높아요 📊", en: "It uses market-cap weighting. Large-cap stocks like Apple and Microsoft have a much higher allocation 📊" },
  },
  {
    id: "q045",
    difficulty: 1,
    tag: { ko: "📦 ETF", en: "📦 ETF" },
    q: { ko: "ETF는 일반 뮤추얼펀드에 비해 최소 투자 금액 제한이 낮다", en: "ETFs have lower minimum investment requirements compared to typical mutual funds" },
    answer: true,
    explain: { ko: "뮤추얼펀드는 최소 수백~수천 달러가 필요하지만 ETF는 1주부터 살 수 있어요 💡", en: "Mutual funds often require hundreds to thousands of dollars minimum, while ETFs can be purchased starting from 1 share 💡" },
  },
  {
    id: "q046",
    difficulty: 1,
    tag: { ko: "📦 ETF", en: "📦 ETF" },
    q: { ko: "채권 ETF(BND, AGG 등)는 일반적으로 주식 ETF보다 가격 변동성이 낮다", en: "Bond ETFs (like BND, AGG) generally have lower price volatility than stock ETFs" },
    answer: true,
    explain: { ko: "채권은 주식보다 안정적인 자산이기 때문에 채권 ETF 가격도 주식 ETF보다 덜 출렁여요 📉", en: "Since bonds are more stable than stocks, bond ETF prices fluctuate less than stock ETF prices 📉" },
  },
  {
    id: "q047",
    difficulty: 1,
    tag: { ko: "📦 ETF", en: "📦 ETF" },
    q: { ko: "SCHD ETF는 미국 고배당 우량주에 투자하는 인기 배당 ETF다", en: "SCHD ETF is a popular dividend ETF that invests in high-quality, high-dividend US stocks" },
    answer: true,
    explain: { ko: "Schwab U.S. Dividend Equity ETF. 배당 성장과 재무 건전성 기준으로 종목을 선별해요 💰", en: "Schwab U.S. Dividend Equity ETF — selects stocks based on dividend growth and financial health 💰" },
  },
  {
    id: "q048",
    difficulty: 1,
    tag: { ko: "📦 ETF", en: "📦 ETF" },
    q: { ko: "ETF 한 종목에 투자하면 자동으로 수십~수백 개 기업에 분산 투자하는 효과가 생긴다", en: "Investing in a single ETF automatically diversifies you across dozens to hundreds of companies" },
    answer: true,
    explain: { ko: "SPY 1주만 사도 미국 대형주 500개에 분산 투자하는 효과가 있어요 🎯", en: "Buying just 1 share of SPY gives you exposure to 500 large-cap US companies 🎯" },
  },
  {
    id: "q049",
    difficulty: 1,
    tag: { ko: "📦 ETF", en: "📦 ETF" },
    q: { ko: "미국에 상장된 ETF는 미국 국적을 가진 사람만 구매할 수 있다", en: "US-listed ETFs can only be purchased by US citizens" },
    answer: false,
    explain: { ko: "외국인도 미국 주식과 ETF를 구매할 수 있어요. 한국인도 해외 증권계좌로 미국 ETF를 살 수 있어요 🌍", en: "Non-US citizens can also buy US stocks and ETFs. Koreans can purchase US ETFs through overseas brokerage accounts 🌍" },
  },
  {
    id: "q050",
    difficulty: 1,
    tag: { ko: "📦 ETF", en: "📦 ETF" },
    q: { ko: "ETF의 NAV(순자산가치)와 시장 거래 가격은 항상 정확히 일치하지는 않는다", en: "An ETF's NAV (Net Asset Value) and its market trading price don't always match exactly" },
    answer: true,
    explain: { ko: "수요·공급에 따라 ETF가 NAV 대비 소폭 프리미엄 또는 디스카운트로 거래될 수 있어요 📊", en: "ETFs can trade at a small premium or discount to their NAV depending on supply and demand 📊" },
  },

  // ── 배당 q051-q070 ────────────────────────────
  {
    id: "q051",
    difficulty: 1,
    tag: "💵 배당",
    q: "배당금(Dividend)이란 기업이 벌어들인 이익의 일부를 주주에게 나눠주는 것이다",
    answer: true,
    explain: "기업이 돈을 잘 벌면 주주에게 보상으로 현금을 지급해요. 투자 수익의 한 형태예요 💵",
  },
  {
    id: "q052",
    difficulty: 1,
    tag: "💵 배당",
    q: "배당 기준일(Record Date)에 주식을 보유한 주주만 해당 회차 배당금을 받을 수 있다",
    answer: true,
    explain: "기준일에 주주 명부에 이름이 올라 있어야 배당금을 받을 수 있어요 📋",
  },
  {
    id: "q053",
    difficulty: 1,
    tag: "💵 배당",
    q: "배당락일(Ex-Dividend Date)에 주식을 매수해도 그 회차 배당금을 받을 수 있다",
    answer: false,
    explain: "배당락일에는 이미 배당 권리가 분리돼요. 배당을 받으려면 배당락일 전날까지 매수해야 해요 ⚠️",
  },
  {
    id: "q054",
    difficulty: 1,
    tag: "💵 배당",
    q: "미국 기업 중에는 매달 배당금을 지급하는 월배당 기업도 있다",
    answer: true,
    explain: "리얼티인컴(O), 메인스트리트 캐피털(MAIN) 등이 대표적인 월배당 기업이에요 📅",
  },
  {
    id: "q055",
    difficulty: 1,
    tag: "💵 배당",
    q: "배당수익률이 높을수록 무조건 좋은 투자 기회다",
    answer: false,
    explain: "배당수익률=배당금÷주가이므로, 주가 폭락이 원인일 수 있어요. '배당 함정'을 주의해야 해요 ⚠️",
  },
  {
    id: "q056",
    difficulty: 1,
    tag: "💵 배당",
    q: "배당재투자(DRIP: Dividend Reinvestment Plan)는 배당금으로 같은 주식을 자동으로 재매입하는 방식이다",
    answer: true,
    explain: "복리 효과를 극대화하는 방법이에요. 배당으로 주식이 늘고, 그 주식에서 배당이 또 나와요 🔄",
  },
  {
    id: "q057",
    difficulty: 1,
    tag: "💵 배당",
    q: "한국 투자자가 미국 주식 배당금을 받으면 미국에서 15%의 배당소득세가 원천징수된다",
    answer: true,
    explain: "한미 조세조약에 따라 한국인은 15% 배당세를 납부해요. 한국 종합소득세 신고 시 공제 가능해요 💸",
  },
  {
    id: "q058",
    difficulty: 1,
    tag: "💵 배당",
    q: "기업이 배당금을 삭감하면 일반적으로 주가가 하락하는 경향이 있다",
    answer: true,
    explain: "배당 삭감은 기업 재무 상황 악화 신호로 받아들여지므로 시장은 부정적으로 반응해요 📉",
  },
  {
    id: "q059",
    difficulty: 1,
    tag: "💵 배당",
    q: "미국 배당주는 보통 분기(3개월)마다 배당금을 지급한다",
    answer: true,
    explain: "1년에 4번 지급하는 것이 미국 배당주의 일반적인 패턴이에요 📅",
  },
  {
    id: "q060",
    difficulty: 1,
    tag: "💵 배당",
    q: "배당수익률(Dividend Yield)은 연간 배당금을 현재 주가로 나눈 비율이다",
    answer: true,
    explain: "예: 주가 100달러에 연 배당 3달러이면 배당수익률은 3%예요 📊",
  },
  {
    id: "q061",
    difficulty: 1,
    tag: "💵 배당",
    q: "배당금은 현금 외에 주식(주식 배당) 형태로 지급되기도 한다",
    answer: true,
    explain: "현금 대신 회사 주식을 추가로 나눠주는 방식도 있어요. 현금 유출 없이 주주에게 보상하는 방법이에요 📄",
  },
  {
    id: "q062",
    difficulty: 1,
    tag: "💵 배당",
    q: "배당을 주지 않는 기업은 나쁜 기업이라고 볼 수 있다",
    answer: false,
    explain: "아마존, 구글, 버크셔해서웨이도 배당을 안 줘요. 이익을 사업 재투자에 쓰는 성장 전략이에요 💡",
  },
  {
    id: "q063",
    difficulty: 1,
    tag: "💵 배당",
    q: "워런 버핏의 버크셔해서웨이(Berkshire Hathaway)는 주주에게 정기적으로 배당금을 지급한다",
    answer: false,
    explain: "버크셔는 배당을 지급하지 않아요. 버핏은 현금을 자사주 매입과 기업 인수에 활용하는 방침이에요 🐧",
  },
  {
    id: "q064",
    difficulty: 1,
    tag: "💵 배당",
    q: "배당 귀족주(Dividend Aristocrat)는 S&P500 기업 중 25년 이상 연속으로 배당을 늘린 기업이다",
    answer: true,
    explain: "코카콜라, 존슨앤드존슨, P&G 등이 해당해요. 재무 안정성의 상징으로 여겨져요 👑",
  },
  {
    id: "q065",
    difficulty: 1,
    tag: "💵 배당",
    q: "한국 주식은 일반적으로 미국 주식에 비해 배당 지급 횟수가 적다",
    answer: true,
    explain: "한국은 연 1회(결산 배당)가 관행이에요. 미국은 분기 배당(연 4회)이 일반적이에요 🇰🇷",
  },
  {
    id: "q066",
    difficulty: 1,
    tag: "💵 배당",
    q: "배당 성장률이 꾸준한 기업은 인플레이션으로 인한 구매력 하락에 대응하는 데 유리하다",
    answer: true,
    explain: "배당이 매년 늘어나면 물가 상승에도 실질 수익을 유지하거나 높일 수 있어요 📈",
  },
  {
    id: "q067",
    difficulty: 1,
    tag: "💵 배당",
    q: "적자를 기록한 기업도 이전에 쌓아둔 이익잉여금으로 배당을 지급할 수 있다",
    answer: true,
    explain: "단, 이런 상황이 반복되면 재무 건전성에 문제가 생기고 결국 배당 삭감으로 이어질 수 있어요 ⚠️",
  },
  {
    id: "q068",
    difficulty: 1,
    tag: "💵 배당",
    q: "배당 지급일(Payment Date)은 배당 기준일(Record Date)과 항상 같은 날이다",
    answer: false,
    explain: "기준일에 주주를 확인하고, 실제 돈이 계좌에 입금되는 지급일(Payment Date)은 별도로 있어요 📅",
  },
  {
    id: "q069",
    difficulty: 1,
    tag: "💵 배당",
    q: "'배당성향'이란 기업의 순이익 중 배당금으로 지급하는 비율이다",
    answer: true,
    explain: "배당성향 50% = 순이익의 절반을 주주 배당으로 지급한다는 의미예요 📊",
  },
  {
    id: "q070",
    difficulty: 1,
    tag: "💵 배당",
    q: "배당금을 많이 지급하는 기업은 그만큼 사업 재투자에 쓸 여력이 줄어든다",
    answer: true,
    explain: "배당과 재투자는 트레이드오프 관계예요. 성장보다 주주 환원을 중시하는 선택이에요 ⚖️",
  },

  // ── 인덱스펀드 q071-q085 ──────────────────────
  {
    id: "q071",
    difficulty: 1,
    tag: "📈 인덱스펀드",
    q: "인덱스펀드(Index Fund)는 특정 주가지수를 그대로 따라가도록 설계된 펀드다",
    answer: true,
    explain: "S&P500 인덱스펀드는 S&P500 지수 수익률과 최대한 동일하게 운용돼요 📊",
  },
  {
    id: "q072",
    difficulty: 1,
    tag: "📈 인덱스펀드",
    q: "인덱스펀드는 펀드매니저가 시장을 분석해 적극적으로 종목을 선택하는 펀드다",
    answer: false,
    explain: "인덱스펀드는 패시브(수동적) 투자예요. 지수를 그대로 복제할 뿐 별도 분석을 하지 않아요 🤖",
  },
  {
    id: "q073",
    difficulty: 1,
    tag: "📈 인덱스펀드",
    q: "인덱스펀드는 일반적으로 액티브펀드보다 운용 수수료가 낮다",
    answer: true,
    explain: "별도 리서치·분석이 없으니 비용이 적어요. 운용보수가 0.03~0.1% 수준인 경우도 많아요 💰",
  },
  {
    id: "q074",
    difficulty: 1,
    tag: "📈 인덱스펀드",
    q: "장기적으로 대부분의 액티브펀드는 S&P500 인덱스펀드의 수익률을 이기지 못한다는 연구 결과가 있다",
    answer: true,
    explain: "S&P 연구에 따르면 15년간 약 90% 이상의 액티브펀드가 S&P500 인덱스펀드에 뒤처졌어요 📊",
  },
  {
    id: "q075",
    difficulty: 1,
    tag: "📈 인덱스펀드",
    q: "인덱스펀드는 지수 수익률보다 더 높은 초과 수익을 목표로 운용된다",
    answer: false,
    explain: "인덱스펀드의 목표는 초과 수익이 아닌 지수 수익률을 최대한 정확히 복제하는 것이에요 🎯",
  },
  {
    id: "q076",
    difficulty: 1,
    tag: "📈 인덱스펀드",
    q: "뱅가드(Vanguard)는 인덱스펀드를 대중화한 자산운용사로 낮은 수수료로 유명하다",
    answer: true,
    explain: "1975년 존 보글이 창립했고, 투자자가 곧 오너인 독특한 구조로 저비용을 유지해요 🏢",
  },
  {
    id: "q077",
    difficulty: 1,
    tag: "📈 인덱스펀드",
    q: "존 보글(John Bogle)은 1976년 세계 최초의 소매 인덱스 뮤추얼펀드를 출시했다",
    answer: true,
    explain: "Vanguard 500 Index Fund가 그 주인공이에요. 존 보글은 '인덱스펀드의 아버지'로 불려요 🏆",
  },
  {
    id: "q078",
    difficulty: 1,
    tag: "📈 인덱스펀드",
    q: "인덱스펀드는 주식 지수만 추종하며 채권 인덱스펀드는 존재하지 않는다",
    answer: false,
    explain: "채권, 부동산, 원자재 등 다양한 자산군의 지수를 추종하는 인덱스펀드도 있어요 📊",
  },
  {
    id: "q079",
    difficulty: 1,
    tag: "📈 인덱스펀드",
    q: "인덱스펀드는 지수 구성 종목이 변경되면 자동으로 포트폴리오를 조정한다",
    answer: true,
    explain: "S&P500에서 A기업이 제외되고 B기업이 편입되면 인덱스펀드도 자동으로 반영해요 🔄",
  },
  {
    id: "q080",
    difficulty: 1,
    tag: "📈 인덱스펀드",
    q: "S&P500 인덱스펀드에 투자하면 미국 경제 성장의 수혜를 간접적으로 받을 수 있다",
    answer: true,
    explain: "미국 대형주 500개에 분산 투자하므로 미국 경제가 성장하면 자연스럽게 수익이 생겨요 🇺🇸",
  },
  {
    id: "q081",
    difficulty: 1,
    tag: "📈 인덱스펀드",
    q: "인덱스펀드는 지수에서 특정 기업이 제외되면 해당 기업 주식을 자동으로 매도한다",
    answer: true,
    explain: "지수를 충실히 복제하는 것이 목표이므로 구성 변경 시 자동으로 매매가 발생해요 📊",
  },
  {
    id: "q082",
    difficulty: 1,
    tag: "📈 인덱스펀드",
    q: "전 세계 주식에 분산 투자하는 글로벌 인덱스펀드(예: VT)도 존재한다",
    answer: true,
    explain: "VT(Vanguard Total World Stock ETF)는 전 세계 약 9,000개 이상의 기업에 투자해요 🌍",
  },
  {
    id: "q083",
    difficulty: 1,
    tag: "📈 인덱스펀드",
    q: "인덱스펀드는 개별 기업을 분석할 필요가 없어 초보 투자자도 쉽게 접근할 수 있다",
    answer: true,
    explain: "시장 전체를 사는 개념이라 어떤 기업이 오를지 고민하지 않아도 돼요 😊",
  },
  {
    id: "q084",
    difficulty: 1,
    tag: "📈 인덱스펀드",
    q: "인덱스펀드는 지수가 하락하면 함께 손실이 발생할 수 있다",
    answer: true,
    explain: "지수를 그대로 복제하므로 지수가 10% 내리면 인덱스펀드도 약 10% 손실이 나요 📉",
  },
  {
    id: "q085",
    difficulty: 1,
    tag: "📈 인덱스펀드",
    q: "워런 버핏은 자신의 유언장에 유산의 일부를 S&P500 인덱스펀드에 투자하도록 명시했다",
    answer: true,
    explain: "90%는 S&P500 인덱스펀드에, 10%는 단기 국채에 투자하라고 유언에 남겼어요 🐘",
  },

  // ── 기초 투자 개념 q086-q100 ──────────────────
  {
    id: "q086",
    difficulty: 1,
    tag: "💡 투자 개념",
    q: "증권사 앱(MTS)을 이용하면 스마트폰으로 주식과 ETF를 거래할 수 있다",
    answer: true,
    explain: "키움증권, 미래에셋 앱(국내)과 찰스슈왑, 피델리티 앱(해외) 등으로 언제 어디서나 거래해요 📱",
  },
  {
    id: "q087",
    difficulty: 1,
    tag: "💡 투자 개념",
    q: "미국 주식에 투자하려면 원화를 미국 달러로 환전해야 한다",
    answer: true,
    explain: "원화로 달러를 매수한 뒤 그 달러로 미국 주식이나 ETF를 구매해요 💱",
  },
  {
    id: "q088",
    difficulty: 1,
    tag: "💡 투자 개념",
    q: "주식 포트폴리오(Portfolio)란 내가 보유한 여러 투자 종목들의 모음을 말한다",
    answer: true,
    explain: "주식, ETF, 채권 등 다양한 자산을 한 바구니에 담은 것을 포트폴리오라고 해요 🗂️",
  },
  {
    id: "q089",
    difficulty: 1,
    tag: "💡 투자 개념",
    q: "손절매란 손실이 발생한 주식을 팔아 더 큰 손실을 방지하는 전략이다",
    answer: true,
    explain: "손해를 확정 짓는 것은 아프지만, 손실이 더 커지는 것을 막는 리스크 관리 방법이에요 ✂️",
  },
  {
    id: "q090",
    difficulty: 1,
    tag: "💡 투자 개념",
    q: "리츠(REITs)는 부동산 자산을 묶어 투자자들이 소액으로 부동산에 간접 투자할 수 있게 하는 상품이다",
    answer: true,
    explain: "Real Estate Investment Trust. 아파트, 쇼핑몰, 창고, 오피스 등에 투자하는 회사예요 🏠",
  },
  {
    id: "q091",
    difficulty: 1,
    tag: "💡 투자 개념",
    q: "ETF의 운용보수(Expense Ratio)는 별도로 청구되지 않고 ETF 자산에서 자동으로 차감된다",
    answer: true,
    explain: "투자자가 직접 내지 않아도 ETF 수익률에 자동 반영돼요. 눈에 보이지 않지만 줄어들어요 📊",
  },
  {
    id: "q092",
    difficulty: 1,
    tag: "💡 투자 개념",
    q: "S&P500 지수는 1957년에 현재의 500개 기업 구성 형태로 처음 만들어졌다",
    answer: true,
    explain: "이전에는 90개 기업 지수였어요. 1957년에 500개로 확대된 현재 형태가 됐어요 📅",
  },
  {
    id: "q093",
    difficulty: 1,
    tag: "💡 투자 개념",
    q: "'분산 투자'란 다양한 종목·자산에 나눠 투자해 한 곳에 집중된 위험을 줄이는 전략이다",
    answer: true,
    explain: "'달걀을 한 바구니에 담지 말라'는 격언처럼, 여러 곳에 나눠 투자하면 위험이 줄어요 🥚",
  },
  {
    id: "q094",
    difficulty: 1,
    tag: "💡 투자 개념",
    q: "복리(Compound Interest)란 이자에 이자가 붙는 방식으로, 투자 기간이 길수록 효과가 커진다",
    answer: true,
    explain: "연 10% 수익으로 30년 운용하면 원금이 17배 이상 불어나요. 시간이 최고의 무기예요 ⏰",
  },
  {
    id: "q095",
    difficulty: 1,
    tag: "💡 투자 개념",
    q: "달러 코스트 에버리징(DCA)은 시장 타이밍을 무시하고 정기적으로 일정 금액을 투자하는 방법이다",
    answer: true,
    explain: "매월 일정 금액씩 꾸준히 투자하면 평균 매입 단가를 낮추고 감정적 투자를 막을 수 있어요 📅",
  },
  {
    id: "q096",
    difficulty: 1,
    tag: "💡 투자 개념",
    q: "같은 S&P500 지수를 추종하더라도 SPY, VOO, IVV의 수익률은 운용보수 차이로 미세하게 다를 수 있다",
    answer: true,
    explain: "VOO(연 0.03%)가 SPY(연 0.0945%)보다 보수가 낮아 장기적으로 수익 차이가 생길 수 있어요 📊",
  },
  {
    id: "q097",
    difficulty: 1,
    tag: "💡 투자 개념",
    q: "인덱스펀드와 ETF는 같은 지수를 추종하더라도 완전히 동일한 금융 상품이다",
    answer: false,
    explain: "인덱스펀드도 ETF 형태가 있지만, 뮤추얼펀드 형태는 실시간 거래가 안 돼요. 구조가 달라요 💡",
  },
  {
    id: "q098",
    difficulty: 1,
    tag: "💡 투자 개념",
    q: "주식 투자에서 '리밸런싱'이란 목표 비율이 흐트러진 포트폴리오를 원래 비율로 되돌리는 것이다",
    answer: true,
    explain: "주식 70%, 채권 30% 비율이 주가 상승으로 80:20이 되면 일부를 팔아 목표 비율로 맞춰요 ⚖️",
  },
  {
    id: "q099",
    difficulty: 1,
    tag: "💡 투자 개념",
    q: "인덱스펀드에 투자하는 것은 시장 전체를 통째로 사는 것과 유사한 효과가 있다",
    answer: true,
    explain: "S&P500 인덱스펀드 하나로 미국 경제를 대표하는 500개 기업 전체에 투자하는 효과가 있어요 📈",
  },
  {
    id: "q100",
    difficulty: 1,
    tag: "💡 투자 개념",
    q: "주식 시장에서 '매도'란 보유한 주식을 시장에 파는 행위를 말한다",
    answer: true,
    explain: "매수(사는 것)의 반대 개념으로, 보유 중인 주식을 시장 참여자에게 파는 행위예요 💼",
  },

  // ════════════════════════════════════════════════
  //  DIFFICULTY 2 — 중급 (Lv 5-7)
  // ════════════════════════════════════════════════

  {
    id: 201,
    difficulty: 2,
    tag: "📊 주식 중급",
    q: "PER(주가수익비율)이 낮다고 항상 저평가된 좋은 주식이다",
    answer: false,
    explain: "PER이 낮아도 성장 둔화, 업황 악화, 구조적 문제가 있으면 나쁜 투자일 수 있어요 📉",
  },
  {
    id: 202,
    difficulty: 2,
    tag: "📊 주식 중급",
    q: "시가총액(Market Cap) = 주가 × 발행 주식 수",
    answer: true,
    explain: "주가가 100달러이고 주식이 1억 주면 시가총액은 100억 달러예요 💰",
  },
  {
    id: 203,
    difficulty: 2,
    tag: "📊 주식 중급",
    q: "주가가 하락하면 배당수익률(Dividend Yield)은 올라간다",
    answer: true,
    explain: "배당수익률 = 배당금 ÷ 주가. 배당금이 같아도 주가가 내리면 수익률은 높아져요 📈",
  },
  {
    id: 204,
    difficulty: 2,
    tag: "📊 주식 중급",
    q: "주식 분할(Stock Split)을 하면 기업의 시가총액이 증가한다",
    answer: false,
    explain: "주식 분할은 파이를 작은 조각으로 나누는 것. 총 가치(시가총액)는 변하지 않아요 🍰",
  },
  {
    id: 205,
    difficulty: 2,
    tag: "📊 주식 중급",
    q: "공매도(Short Selling)는 주가가 하락할 때 수익을 내는 전략이다",
    answer: true,
    explain: "주식을 빌려서 팔고, 주가가 떨어지면 싸게 다시 사서 갚는 방식이에요 📉",
  },
  {
    id: 206,
    difficulty: 2,
    tag: "📊 주식 중급",
    q: "EPS(주당순이익)가 높을수록 일반적으로 기업 수익성이 좋다는 신호다",
    answer: true,
    explain: "EPS = 순이익 ÷ 발행주식수. 높을수록 주주 1주당 더 많은 이익을 벌어들이는 거예요 📊",
  },
  {
    id: 207,
    difficulty: 2,
    tag: "📊 주식 중급",
    q: "ROE(자기자본이익률)가 높을수록 주주 입장에서 더 효율적인 기업이다",
    answer: true,
    explain: "ROE = 순이익 ÷ 자기자본. 같은 돈으로 더 많은 이익을 내니 주주에게 유리해요 💪",
  },
  {
    id: 208,
    difficulty: 2,
    tag: "📊 주식 중급",
    q: "배당 귀족주(Dividend Aristocrat)는 10년 이상 연속으로 배당을 늘린 기업이다",
    answer: false,
    explain: "S&P 배당 귀족 기준은 25년 이상 연속 배당 인상이에요. 10년은 배당 성취자(Achiever) 기준이에요 👑",
  },
  {
    id: 209,
    difficulty: 2,
    tag: "📊 주식 중급",
    q: "코스피(KOSPI)와 코스닥(KOSDAQ)은 서로 다른 주식 시장이다",
    answer: true,
    explain: "코스피는 대형주 중심, 코스닥은 중소·벤처·기술주 중심의 시장이에요 🇰🇷",
  },
  {
    id: 210,
    difficulty: 2,
    tag: "💡 투자 중급",
    q: "달러 강세는 미국 수출 기업의 실적에 불리하게 작용한다",
    answer: true,
    explain: "달러 강세 → 해외 매출을 달러로 환산하면 줄어들어요. 반대로 달러 약세가 수출 기업에 유리해요 💱",
  },
  {
    id: 211,
    difficulty: 2,
    tag: "💡 투자 중급",
    q: "연방준비제도(Fed)가 기준금리를 올리면 일반적으로 주가는 하락 압력을 받는다",
    answer: true,
    explain: "금리↑ → 채권 매력↑, 기업 대출 비용↑ → 주식 매력↓. 성장주에 특히 큰 타격이에요 📊",
  },
  {
    id: 212,
    difficulty: 2,
    tag: "💡 투자 중급",
    q: "채권 가격과 채권 금리(수익률)는 반대 방향으로 움직인다",
    answer: true,
    explain: "금리가 오르면 기존 채권의 가격이 내려가요. 시소처럼 반비례 관계예요 📉",
  },
  {
    id: 213,
    difficulty: 2,
    tag: "💡 투자 중급",
    q: "달러 코스트 에버리징(DCA)은 시장 저점을 예측해서 투자하는 전략이다",
    answer: false,
    explain: "DCA는 타이밍 관계없이 일정 금액을 정기적으로 투자하는 방법이에요. 시장 예측과 정반대 개념이에요 📅",
  },
  {
    id: 214,
    difficulty: 2,
    tag: "💡 투자 중급",
    q: "복리 효과는 투자 기간이 길수록 더 강력하게 나타난다",
    answer: true,
    explain: "연 10% 수익을 30년 복리로 굴리면 원금의 17배! 시간이 최고의 투자 무기예요 ⏰",
  },
  {
    id: 215,
    difficulty: 2,
    tag: "💡 투자 중급",
    q: "인플레이션이 높아지면 실질 채권 수익률은 하락한다",
    answer: true,
    explain: "실질수익률 = 명목금리 - 인플레이션. 물가 상승이 채권 실질 수익을 갉아먹어요 🔥",
  },
  {
    id: 216,
    difficulty: 2,
    tag: "💡 투자 중급",
    q: "배당수익률이 매우 높은 주식(10% 이상)은 항상 좋은 투자 기회다",
    answer: false,
    explain: "초고배당은 기업 위기나 주가 폭락 신호일 수 있어요. '배당 함정(Dividend Trap)'을 조심해야 해요 ⚠️",
  },
  {
    id: 217,
    difficulty: 2,
    tag: "💡 투자 중급",
    q: "나스닥100 지수를 추종하는 대표 ETF는 QQQ다",
    answer: true,
    explain: "Invesco QQQ Trust. 애플·마이크로소프트·엔비디아 등 나스닥 상위 100개 기업에 투자해요 💻",
  },
  {
    id: 218,
    difficulty: 2,
    tag: "🤖 테크 중급",
    q: "TSMC는 세계 반도체 파운드리(위탁생산) 시장 점유율 1위 기업이다",
    answer: true,
    explain: "대만 기반 TSMC는 전 세계 파운드리 시장의 약 55%를 점유하는 압도적 1위예요 🇹🇼",
  },
  {
    id: 219,
    difficulty: 2,
    tag: "🤖 테크 중급",
    q: "레버리지 ETF(2배·3배)는 장기 보유 시 기초지수의 정확한 배수 수익을 보장한다",
    answer: false,
    explain: "매일 리셋되는 구조 때문에 변동성이 클수록 '변동성 손실'이 생겨 장기 수익이 왜곡돼요 ⚡",
  },
  {
    id: 220,
    difficulty: 2,
    tag: "🤖 테크 중급",
    q: "ARM 홀딩스의 칩 설계는 대부분의 스마트폰에 사용된다",
    answer: true,
    explain: "애플, 삼성, 퀄컴 등이 모두 ARM 기반 아키텍처로 칩을 설계해요 📱",
  },
  {
    id: 221,
    difficulty: 2,
    tag: "📊 주식 중급",
    q: "소비자물가지수(CPI)가 상승하면 인플레이션이 높아지는 것이다",
    answer: true,
    explain: "CPI는 물가 수준을 측정하는 지표예요. CPI↑ = 인플레이션↑ = 화폐 구매력↓ 📊",
  },

  // ── RSI q101-q115 ─────────────────────────────
  {
    id: "q101",
    difficulty: 2,
    tag: "📉 기술적 분석 — RSI",
    q: "RSI(상대강도지수)는 일정 기간의 주가 상승폭과 하락폭을 비교해 과매수·과매도를 측정하는 지표다",
    answer: true,
    explain: "Relative Strength Index. 가격 변화의 속도와 크기를 0~100 범위로 나타내요 📊",
  },
  {
    id: "q102",
    difficulty: 2,
    tag: "📉 기술적 분석 — RSI",
    q: "RSI는 0부터 100 사이의 값을 가지는 지표다",
    answer: true,
    explain: "모든 기간이 상승이면 100, 모든 기간이 하락이면 0에 가까워요. 50이 중립선이에요 📊",
  },
  {
    id: "q103",
    difficulty: 2,
    tag: "📉 기술적 분석 — RSI",
    q: "RSI 값이 70 이상이면 일반적으로 과매수(Overbought) 구간으로 본다",
    answer: true,
    explain: "과매수 = 단기간에 너무 많이 올랐다는 신호. 조정 가능성을 염두에 두는 구간이에요 ⚠️",
  },
  {
    id: "q104",
    difficulty: 2,
    tag: "📉 기술적 분석 — RSI",
    q: "RSI 값이 30 이하이면 일반적으로 과매도(Oversold) 구간으로 본다",
    answer: true,
    explain: "과매도 = 단기간에 너무 많이 떨어졌다는 신호. 반등 가능성을 기대하는 구간이에요 📈",
  },
  {
    id: "q105",
    difficulty: 2,
    tag: "📉 기술적 분석 — RSI",
    q: "RSI가 70을 넘으면 즉시 주가가 반드시 하락한다",
    answer: false,
    explain: "강한 추세장에서는 RSI가 70 이상을 오랫동안 유지하며 계속 오를 수 있어요. 참고 지표일 뿐이에요 💡",
  },
  {
    id: "q106",
    difficulty: 2,
    tag: "📉 기술적 분석 — RSI",
    q: "RSI의 기본 계산 기간은 14일이다",
    answer: true,
    explain: "개발자 웰스 와일더가 제안한 기본값이에요. 기간을 짧게 하면 민감해지고 길면 둔감해져요 📅",
  },
  {
    id: "q107",
    difficulty: 2,
    tag: "📉 기술적 분석 — RSI",
    q: "RSI는 가격 추세 방향만 파악하는 '추세 추종 지표'다",
    answer: false,
    explain: "RSI는 모멘텀 오실레이터(Momentum Oscillator)예요. 추세 강도와 과매수·과매도를 측정해요 🔄",
  },
  {
    id: "q108",
    difficulty: 2,
    tag: "📉 기술적 분석 — RSI",
    q: "RSI 강세 다이버전스(Bullish Divergence)란 주가는 신저점을 만드는데 RSI는 더 높은 저점을 형성하는 현상이다",
    answer: true,
    explain: "주가와 RSI의 방향이 엇갈리면 추세 전환 신호로 봐요. 하락 모멘텀이 약해지는 신호예요 📊",
  },
  {
    id: "q109",
    difficulty: 2,
    tag: "📉 기술적 분석 — RSI",
    q: "RSI가 50 이상이면 상승 모멘텀이 우세한 상태라고 볼 수 있다",
    answer: true,
    explain: "50선은 RSI의 중립선이에요. 50 이상 = 상승 우세, 50 이하 = 하락 우세로 해석해요 📈",
  },
  {
    id: "q110",
    difficulty: 2,
    tag: "📉 기술적 분석 — RSI",
    q: "RSI는 모든 시장 상황에서 완벽하게 신뢰할 수 있는 매매 신호를 제공한다",
    answer: false,
    explain: "RSI는 보조지표예요. 횡보장, 추세장 여부에 따라 신뢰도가 달라지고 오신호도 발생해요 ⚠️",
  },
  {
    id: "q111",
    difficulty: 2,
    tag: "📉 기술적 분석 — RSI",
    q: "RSI 계산 기간을 짧게 설정할수록 민감도가 높아져 신호가 더 자주 발생한다",
    answer: true,
    explain: "기간 7일 RSI는 14일보다 변동이 잦아 단기 트레이더에게 유용하고, 오신호도 많아져요 📊",
  },
  {
    id: "q112",
    difficulty: 2,
    tag: "📉 기술적 분석 — RSI",
    q: "RSI 값이 높다는 것은 해당 기간 동안 하락폭보다 상승폭이 더 컸다는 의미다",
    answer: true,
    explain: "RSI = 100 × 평균상승폭 ÷ (평균상승폭 + 평균하락폭). 상승이 강할수록 높아져요 📈",
  },
  {
    id: "q113",
    difficulty: 2,
    tag: "📉 기술적 분석 — RSI",
    q: "RSI는 J. 웰스 와일더(J. Welles Wilder)가 1978년에 개발한 기술적 분석 지표다",
    answer: true,
    explain: "'New Concepts in Technical Trading Systems' 저서에서 처음 소개됐어요 📚",
  },
  {
    id: "q114",
    difficulty: 2,
    tag: "📉 기술적 분석 — RSI",
    q: "강한 추세장에서는 RSI가 과매수·과매도 구간에 오랫동안 머물 수 있다",
    answer: true,
    explain: "강세장에서 RSI 70 이상이 수주~수개월 지속되기도 해요. 추세 강도에 맞게 기준을 조정해요 💡",
  },
  {
    id: "q115",
    difficulty: 2,
    tag: "📉 기술적 분석 — RSI",
    q: "RSI 약세 다이버전스(Bearish Divergence)는 주가가 신고점을 만드는데 RSI는 더 낮은 고점을 형성하는 현상이다",
    answer: true,
    explain: "상승 모멘텀이 약해지는 신호로 해석해요. 주가가 오르는데 RSI가 낮아지면 하락 반전 가능성이 커요 📉",
  },

  // ── MACD q116-q130 ────────────────────────────
  {
    id: "q116",
    difficulty: 2,
    tag: "📉 기술적 분석 — MACD",
    q: "MACD는 두 개의 지수이동평균(EMA) 차이를 이용해 추세와 모멘텀을 분석하는 지표다",
    answer: true,
    explain: "Moving Average Convergence Divergence. 두 이동평균이 가까워지고(수렴) 멀어지는(발산) 것을 분석해요 📊",
  },
  {
    id: "q117",
    difficulty: 2,
    tag: "📉 기술적 분석 — MACD",
    q: "MACD선은 12일 EMA에서 26일 EMA를 뺀 값이다",
    answer: true,
    explain: "기본 설정 12-26-9예요. 12일 단기 EMA와 26일 장기 EMA의 차이로 MACD선을 만들어요 📈",
  },
  {
    id: "q118",
    difficulty: 2,
    tag: "📉 기술적 분석 — MACD",
    q: "MACD선이 시그널선을 아래에서 위로 돌파하면 일반적으로 매수 신호로 본다",
    answer: true,
    explain: "골든크로스 신호예요. 단기 모멘텀이 살아나고 있다는 의미로 해석해요 🟢",
  },
  {
    id: "q119",
    difficulty: 2,
    tag: "📉 기술적 분석 — MACD",
    q: "MACD 히스토그램이 양수(+)라는 것은 MACD선이 시그널선 위에 있다는 의미다",
    answer: true,
    explain: "히스토그램 = MACD선 - 시그널선. 양수면 MACD > 시그널, 음수면 MACD < 시그널이에요 📊",
  },
  {
    id: "q120",
    difficulty: 2,
    tag: "📉 기술적 분석 — MACD",
    q: "MACD의 시그널선은 일반적으로 MACD의 9일 EMA로 계산된다",
    answer: true,
    explain: "MACD선을 다시 9일 지수이동평균을 내면 시그널선이 돼요. 매매 타이밍 판단에 사용해요 📅",
  },
  {
    id: "q121",
    difficulty: 2,
    tag: "📉 기술적 분석 — MACD",
    q: "EMA(지수이동평균)는 SMA(단순이동평균)보다 최근 데이터에 더 높은 가중치를 부여한다",
    answer: true,
    explain: "최신 가격 변화에 더 민감하게 반응해 SMA보다 빠른 추세 파악이 가능해요 ⚡",
  },
  {
    id: "q122",
    difficulty: 2,
    tag: "📉 기술적 분석 — MACD",
    q: "MACD 값이 0보다 크면 단기 EMA가 장기 EMA 위에 있다는 의미다",
    answer: true,
    explain: "MACD = 단기EMA - 장기EMA. 양수면 단기가 장기보다 높아 상승 추세 신호예요 📈",
  },
  {
    id: "q123",
    difficulty: 2,
    tag: "📉 기술적 분석 — MACD",
    q: "MACD선이 시그널선을 위에서 아래로 돌파(데드크로스)하면 매도 신호로 해석한다",
    answer: true,
    explain: "하락 모멘텀이 강해지는 신호예요. 매도 타이밍을 고려하는 구간이에요 🔴",
  },
  {
    id: "q124",
    difficulty: 2,
    tag: "📉 기술적 분석 — MACD",
    q: "MACD 다이버전스란 주가와 MACD가 서로 반대 방향으로 움직이는 현상이다",
    answer: true,
    explain: "주가는 오르는데 MACD는 낮아지면 약세 다이버전스로 하락 반전 경고 신호가 돼요 📉",
  },
  {
    id: "q125",
    difficulty: 2,
    tag: "📉 기술적 분석 — MACD",
    q: "MACD는 방향성 없는 횡보장(박스권)에서 가장 신뢰할 수 있는 신호를 제공한다",
    answer: false,
    explain: "MACD는 추세 추종 지표예요. 추세가 뚜렷한 추세장에서 유효하고 횡보장에선 오신호가 많아요 ⚠️",
  },
  {
    id: "q126",
    difficulty: 2,
    tag: "📉 기술적 분석 — MACD",
    q: "MACD 히스토그램이 점점 줄어드는 것은 현재 방향의 모멘텀이 약해지고 있다는 신호다",
    answer: true,
    explain: "히스토그램 막대가 작아진다 = MACD선과 시그널선이 가까워진다 = 추세 약화 신호예요 📊",
  },
  {
    id: "q127",
    difficulty: 2,
    tag: "📉 기술적 분석 — MACD",
    q: "MACD는 제럴드 아펠(Gerald Appel)이 1970년대에 개발한 기술적 분석 지표다",
    answer: true,
    explain: "주식 분석가인 아펠이 트레이딩 시스템으로 개발했어요. 현재까지 가장 널리 쓰이는 지표 중 하나예요 📚",
  },
  {
    id: "q128",
    difficulty: 2,
    tag: "📉 기술적 분석 — MACD",
    q: "골든크로스(Golden Cross)는 단기 이동평균선이 장기 이동평균선을 아래에서 위로 돌파하는 현상이다",
    answer: true,
    explain: "50일선이 200일선을 위로 뚫으면 강한 상승 신호로 봐요. 반대는 데드크로스예요 🌟",
  },
  {
    id: "q129",
    difficulty: 2,
    tag: "📉 기술적 분석 — MACD",
    q: "MACD는 후행 지표(Lagging Indicator)이므로 미래 주가를 정확히 예측하는 데 한계가 있다",
    answer: true,
    explain: "이동평균을 기반으로 하기 때문에 과거 데이터를 반영해요. 신호가 항상 늦게 나타날 수 있어요 ⏱️",
  },
  {
    id: "q130",
    difficulty: 2,
    tag: "📉 기술적 분석 — MACD",
    q: "MACD 히스토그램이 마이너스(-)에서 양수(+)로 전환되면 매수 신호로 해석할 수 있다",
    answer: true,
    explain: "히스토그램 부호 전환 = MACD선과 시그널선의 크로스 발생을 의미해요 📈",
  },

  // ── PER q131-q145 ─────────────────────────────
  {
    id: "q131",
    difficulty: 2,
    tag: "💹 밸류에이션 — PER",
    q: "PER(주가수익비율)은 주가를 주당순이익(EPS)으로 나눈 값이다",
    answer: true,
    explain: "Price-to-Earnings Ratio. 주가가 이익의 몇 배로 거래되는지를 나타내요 📊",
  },
  {
    id: "q132",
    difficulty: 2,
    tag: "💹 밸류에이션 — PER",
    q: "PER이 높을수록 시장이 해당 기업의 미래 성장성에 높은 기대를 갖고 있다고 볼 수 있다",
    answer: true,
    explain: "투자자가 현재 이익 대비 더 높은 가격을 지불하는 건 미래 성장에 베팅하는 것이에요 🚀",
  },
  {
    id: "q133",
    difficulty: 2,
    tag: "💹 밸류에이션 — PER",
    q: "트레일링 PER(Trailing PER)는 과거 12개월의 실제 이익을 기준으로 계산한다",
    answer: true,
    explain: "이미 발생한 이익을 쓰기 때문에 객관적이에요. 반면 포워드 PER는 예상치 기반이에요 📅",
  },
  {
    id: "q134",
    difficulty: 2,
    tag: "💹 밸류에이션 — PER",
    q: "포워드 PER(Forward PER)는 향후 12개월 예상 이익을 기준으로 계산한다",
    answer: true,
    explain: "애널리스트 컨센서스 추정치를 사용해요. 불확실하지만 시장의 기대를 더 잘 반영해요 🔮",
  },
  {
    id: "q135",
    difficulty: 2,
    tag: "💹 밸류에이션 — PER",
    q: "순손실을 기록한 적자 기업의 PER는 음수(-)이거나 계산 자체가 무의미하다",
    answer: true,
    explain: "EPS가 마이너스이면 PER도 의미 없어요. 적자 기업엔 PSR, EV/Sales 등 다른 지표를 써요 📊",
  },
  {
    id: "q136",
    difficulty: 2,
    tag: "💹 밸류에이션 — PER",
    q: "성장주(Growth Stock)는 일반적으로 가치주(Value Stock)보다 PER가 높게 형성된다",
    answer: true,
    explain: "성장주는 미래 이익 기대가 크기 때문에 현재 이익 대비 높은 가격이 붙어요 📈",
  },
  {
    id: "q137",
    difficulty: 2,
    tag: "💹 밸류에이션 — PER",
    q: "동일 업종 내 기업들의 PER를 비교하면 상대적 밸류에이션을 파악할 수 있다",
    answer: true,
    explain: "업종마다 평균 PER가 다르기 때문에 같은 업종끼리 비교해야 의미가 있어요 🔍",
  },
  {
    id: "q138",
    difficulty: 2,
    tag: "💹 밸류에이션 — PER",
    q: "전체 시장 평균 PER가 역사적 평균보다 훨씬 높으면 시장 전반이 고평가됐을 가능성이 있다",
    answer: true,
    explain: "S&P500의 역사적 평균 PER는 약 15~16배예요. 이를 크게 넘으면 거품 우려가 커져요 ⚠️",
  },
  {
    id: "q139",
    difficulty: 2,
    tag: "💹 밸류에이션 — PER",
    q: "PER는 기업의 부채 수준을 직접 반영하는 지표다",
    answer: false,
    explain: "PER = 주가 ÷ EPS로, 부채는 직접 포함되지 않아요. 부채까지 고려하려면 EV/EBITDA를 써요 💡",
  },
  {
    id: "q140",
    difficulty: 2,
    tag: "💹 밸류에이션 — PER",
    q: "경기침체기에 기업 이익이 급감하면 PER가 실제보다 높아 보이는 왜곡이 생길 수 있다",
    answer: true,
    explain: "불황 시 EPS가 일시 급락하면 PER가 매우 높게 나와 고평가로 착각할 수 있어요 📉",
  },
  {
    id: "q141",
    difficulty: 2,
    tag: "💹 밸류에이션 — PER",
    q: "PER 20이란 현재 이익 수준이 유지된다면 투자 원금 회수에 약 20년이 걸린다는 의미다",
    answer: true,
    explain: "PER = 회수 연수라고도 해요. 이익이 꾸준히 유지된다는 전제하에 해석하는 방식이에요 ⏳",
  },
  {
    id: "q142",
    difficulty: 2,
    tag: "💹 밸류에이션 — PER",
    q: "은행·보험 등 금융업종의 적정 PER는 일반적으로 기술 성장주보다 낮다",
    answer: true,
    explain: "금융주는 성장성이 낮고 규제 산업이라 낮은 PER가 일반적이에요. 성장주는 40~100배도 있어요 🏦",
  },
  {
    id: "q143",
    difficulty: 2,
    tag: "💹 밸류에이션 — PER",
    q: "같은 PER라도 이익의 질(Quality)과 성장률에 따라 투자 가치 판단이 달라진다",
    answer: true,
    explain: "PER 20인 기업도 이익이 매년 30% 성장한다면 오히려 저평가일 수 있어요. 맥락이 중요해요 🔍",
  },
  {
    id: "q144",
    difficulty: 2,
    tag: "💹 밸류에이션 — PER",
    q: "경기방어주(필수 소비재 등)는 경기민감주보다 PER 변동성이 작은 경향이 있다",
    answer: true,
    explain: "먹고 마시는 생필품은 경기 영향을 덜 받아 이익이 안정적이고 PER도 안정적이에요 🛡️",
  },
  {
    id: "q145",
    difficulty: 2,
    tag: "💹 밸류에이션 — PER",
    q: "PER 계산 시 분모는 주당순이익(EPS)이 아닌 주당 영업이익을 사용한다",
    answer: false,
    explain: "PER = 주가 ÷ 주당순이익(EPS). 영업이익이 아닌 세후 순이익 기준이에요 📊",
  },

  // ── PBR q146-q160 ─────────────────────────────
  {
    id: "q146",
    difficulty: 2,
    tag: "💹 밸류에이션 — PBR",
    q: "PBR(주가순자산비율)은 주가를 주당순자산가치(BPS)로 나눈 값이다",
    answer: true,
    explain: "Price-to-Book Ratio. 시장이 기업의 장부 자산 가치 대비 얼마를 지불하는지 나타내요 📊",
  },
  {
    id: "q147",
    difficulty: 2,
    tag: "💹 밸류에이션 — PBR",
    q: "PBR이 1 미만이면 주가가 장부상 순자산가치보다 낮게 거래되고 있다는 의미다",
    answer: true,
    explain: "이론적으로 지금 당장 청산해도 주가보다 더 많이 받을 수 있다는 뜻이에요 📉",
  },
  {
    id: "q148",
    difficulty: 2,
    tag: "💹 밸류에이션 — PBR",
    q: "PBR이 1 미만이면 항상 좋은 저평가 투자 기회다",
    answer: false,
    explain: "업황 구조적 악화, 자산 가치 훼손, 수익성 문제 등이 원인일 수 있어요. 이유 파악이 먼저예요 ⚠️",
  },
  {
    id: "q149",
    difficulty: 2,
    tag: "💹 밸류에이션 — PBR",
    q: "금융·은행주 분석에는 PER보다 PBR이 더 자주 활용된다",
    answer: true,
    explain: "은행은 대출·예금 등 자산 비중이 크기 때문에 순자산 기반의 PBR이 더 적합해요 🏦",
  },
  {
    id: "q150",
    difficulty: 2,
    tag: "💹 밸류에이션 — PBR",
    q: "브랜드, 특허, 소프트웨어 같은 무형자산이 많은 기술 기업은 PBR이 높게 나오는 경향이 있다",
    answer: true,
    explain: "무형자산의 실제 가치는 장부보다 훨씬 크지만 회계상 반영이 어려워 PBR이 높게 형성돼요 💡",
  },
  {
    id: "q151",
    difficulty: 2,
    tag: "💹 밸류에이션 — PBR",
    q: "BPS(주당순자산가치) = (총자산 - 총부채) ÷ 발행 주식 수",
    answer: true,
    explain: "순자산(자기자본)을 주식 수로 나눈 값이에요. 기업이 청산될 때 주주 1주당 받을 수 있는 금액이에요 📊",
  },
  {
    id: "q152",
    difficulty: 2,
    tag: "💹 밸류에이션 — PBR",
    q: "PBR 1.0은 시장이 해당 기업의 순자산 가치와 동일하게 평가한다는 의미다",
    answer: true,
    explain: "PBR 1.0 = 장부 가치 그대로 시장에서 거래되는 상태예요. 1 이상이면 프리미엄이 붙은 것이에요 📊",
  },
  {
    id: "q153",
    difficulty: 2,
    tag: "💹 밸류에이션 — PBR",
    q: "ROE가 높은 기업은 일반적으로 PBR도 높게 형성되는 경향이 있다",
    answer: true,
    explain: "ROE가 높다 = 자본을 잘 활용해 이익을 낸다 = 시장이 높은 프리미엄 부여 → PBR↑ 📈",
  },
  {
    id: "q154",
    difficulty: 2,
    tag: "💹 밸류에이션 — PBR",
    q: "PBR이 높다고 해서 반드시 고평가된 것은 아니다",
    answer: true,
    explain: "높은 ROE, 탁월한 성장성, 강력한 브랜드 가치라면 높은 PBR이 정당화될 수 있어요 💡",
  },
  {
    id: "q155",
    difficulty: 2,
    tag: "💹 밸류에이션 — PBR",
    q: "업종마다 적정 PBR 기준이 다르므로 동일 업종 내에서 비교하는 것이 중요하다",
    answer: true,
    explain: "제조업 PBR 1~2배, IT 기업 5~20배 등 업종별 기준이 크게 달라요 🔍",
  },
  {
    id: "q156",
    difficulty: 2,
    tag: "💹 밸류에이션 — PBR",
    q: "순자산(자기자본)이 마이너스인 기업의 PBR은 의미 있는 분석이 어렵다",
    answer: true,
    explain: "부채가 자산을 초과하면 순자산이 음수가 돼요. 이때는 PBR 계산 자체가 무의미해요 📊",
  },
  {
    id: "q157",
    difficulty: 2,
    tag: "💹 밸류에이션 — PBR",
    q: "PBR은 기업의 청산 가치 대비 현재 주가 수준을 파악하는 데 유용하다",
    answer: true,
    explain: "기업을 지금 당장 팔면 얼마를 받을 수 있는지와 현재 주가를 비교하는 관점이에요 🏭",
  },
  {
    id: "q158",
    difficulty: 2,
    tag: "💹 밸류에이션 — PBR",
    q: "워런 버핏은 투자 초기에 낮은 PBR의 가치주를 중심으로 투자하는 전략을 사용했다",
    answer: true,
    explain: "스승인 벤저민 그레이엄의 영향으로 자산 대비 저평가된 종목을 발굴했어요. 나중엔 질적 성장에 집중했죠 🐘",
  },
  {
    id: "q159",
    difficulty: 2,
    tag: "💹 밸류에이션 — PBR",
    q: "PBR은 기업의 단기 수익성을 측정하는 지표다",
    answer: false,
    explain: "PBR은 자산 가치 대비 주가를 보는 지표예요. 단기 수익성 측정엔 PER, ROE 등을 사용해요 💡",
  },
  {
    id: "q160",
    difficulty: 2,
    tag: "💹 밸류에이션 — PBR",
    q: "PBR이 높은 기업은 시장이 해당 기업의 미래 성장성과 무형자산을 높이 평가한다는 의미다",
    answer: true,
    explain: "애플의 PBR은 40배 이상이에요. 브랜드·생태계 가치가 장부 자산보다 훨씬 높게 평가된 결과예요 🍎",
  },

  // ── 재무제표 q161-q185 ────────────────────────
  {
    id: "q161",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "재무제표의 핵심 3대 보고서는 손익계산서, 재무상태표(대차대조표), 현금흐름표다",
    answer: true,
    explain: "세 보고서를 함께 보면 기업의 수익성·재무 건전성·현금 상황을 종합적으로 파악할 수 있어요 📊",
  },
  {
    id: "q162",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "손익계산서(Income Statement)는 일정 기간의 수익과 비용을 기록한 보고서다",
    answer: true,
    explain: "분기 또는 연간 단위로 작성돼요. '얼마를 벌고 얼마를 썼나'를 보여주는 성적표예요 📄",
  },
  {
    id: "q163",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "재무상태표(Balance Sheet)는 특정 기간의 누적 이익을 보여주는 보고서다",
    answer: false,
    explain: "재무상태표는 특정 시점(결산일)의 자산·부채·자본 현황을 보여줘요. 누적 이익은 손익계산서예요 💡",
  },
  {
    id: "q164",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "현금흐름표(Cash Flow Statement)는 영업·투자·재무활동 세 가지로 구분된다",
    answer: true,
    explain: "영업(본업), 투자(설비·자산), 재무(차입·배당)로 나눠 현금 흐름을 분류해요 💵",
  },
  {
    id: "q165",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "영업이익(Operating Income) = 매출액 - 매출원가 - 판매관리비",
    answer: true,
    explain: "본업에서 벌어들인 이익이에요. 이자 비용과 세금을 내기 전 수익이에요 📊",
  },
  {
    id: "q166",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "당기순이익이 흑자여도 영업활동 현금흐름이 마이너스일 수 있다",
    answer: true,
    explain: "외상 매출 증가, 재고 급증 등으로 이익은 발생했지만 현금이 안 들어올 수 있어요 ⚠️",
  },
  {
    id: "q167",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "매출총이익(Gross Profit) = 매출액 - 매출원가",
    answer: true,
    explain: "제품·서비스 생산에 직접 들어간 원가만 뺀 이익이에요. 판매관리비는 아직 빼기 전이에요 📊",
  },
  {
    id: "q168",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "재무상태표에서 '자산 = 부채 + 자본'은 항상 성립하는 등식이다",
    answer: true,
    explain: "회계의 기본 등식이에요. 기업의 모든 자산은 타인 자금(부채) 또는 자기 자금(자본)으로 조달돼요 ⚖️",
  },
  {
    id: "q169",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "유동자산(Current Assets)은 1년 이내에 현금화할 수 있는 자산이다",
    answer: true,
    explain: "현금, 단기 예금, 매출채권, 재고자산 등이 여기에 속해요 💰",
  },
  {
    id: "q170",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "유동부채(Current Liabilities)는 1년 이내에 상환해야 하는 부채다",
    answer: true,
    explain: "단기차입금, 매입채무, 미지급비용 등이 여기에 속해요. 유동자산으로 커버 가능한지가 중요해요 📊",
  },
  {
    id: "q171",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "부채비율(D/E Ratio) = 총부채 ÷ 자기자본 × 100으로 계산한다",
    answer: true,
    explain: "100%면 타인 자본과 자기 자본이 같다는 뜻이에요. 높을수록 재무 레버리지가 크고 위험도 커요 📊",
  },
  {
    id: "q172",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "유동비율(Current Ratio)이 높을수록 단기 채무 상환 능력이 좋다는 신호다",
    answer: true,
    explain: "유동비율 = 유동자산 ÷ 유동부채. 200% 이상이면 단기 상환 능력이 양호하다고 봐요 💪",
  },
  {
    id: "q173",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "매출액이 늘어도 비용이 더 빠르게 늘면 순이익은 감소할 수 있다",
    answer: true,
    explain: "매출 성장이 수익성 개선을 보장하지 않아요. 이익률(Margin)도 함께 확인해야 해요 📊",
  },
  {
    id: "q174",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "EBIT는 이자 비용과 법인세를 차감하기 전의 영업이익이다",
    answer: true,
    explain: "Earnings Before Interest and Taxes. 자본 구조와 세금 효과를 제외한 순수 영업 성과를 봐요 📊",
  },
  {
    id: "q175",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "이익잉여금(Retained Earnings)은 기업이 벌어들인 순이익 중 배당 후 사내에 축적한 금액이다",
    answer: true,
    explain: "쌓인 이익잉여금은 재투자, 부채 상환, 자사주 매입 등에 활용돼요 💰",
  },
  {
    id: "q176",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "감가상각비(Depreciation)는 실제 현금 지출 없이 장부에 비용으로 처리하는 항목이다",
    answer: true,
    explain: "건물·기계 등의 가치 감소를 매년 나눠 비용 처리해요. 현금은 안 나가지만 이익은 줄여요 💡",
  },
  {
    id: "q177",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "영업활동 현금흐름이 장기간 지속적으로 마이너스인 기업은 재무 위험 신호일 수 있다",
    answer: true,
    explain: "본업에서 현금을 못 벌면 외부 조달에 의존해야 해요. 지속 가능성을 점검해야 해요 ⚠️",
  },
  {
    id: "q178",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "재고자산(Inventory)은 유동자산에 포함된다",
    answer: true,
    explain: "팔기 위해 보유 중인 상품·원재료예요. 1년 이내에 판매·현금화한다고 보아 유동자산으로 분류해요 📦",
  },
  {
    id: "q179",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "매출총이익률(Gross Margin) = 매출총이익 ÷ 매출액 × 100",
    answer: true,
    explain: "원가 대비 얼마나 마진을 남기는지 보여줘요. 소프트웨어 기업은 80%+, 제조업은 20~40% 수준이에요 📊",
  },
  {
    id: "q180",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "영업이익률(Operating Margin)이 높을수록 기업이 영업을 더 효율적으로 하고 있다는 의미다",
    answer: true,
    explain: "영업이익률 = 영업이익 ÷ 매출액. 같은 매출에서 더 많은 이익을 남기는 거예요 📈",
  },
  {
    id: "q181",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "투자활동 현금흐름이 마이너스이면 항상 나쁜 신호다",
    answer: false,
    explain: "공장 증설, 신규 설비 투자, M&A 등 성장을 위한 지출이면 긍정적 신호일 수 있어요 🏭",
  },
  {
    id: "q182",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "재무활동 현금흐름에는 배당금 지급, 자사주 매입, 신규 차입 등이 포함된다",
    answer: true,
    explain: "돈을 어떻게 조달하고 주주에게 어떻게 환원하는지를 보여주는 활동이에요 💼",
  },
  {
    id: "q183",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "당기순이익이 높다고 해서 그 기업의 현금 상황도 반드시 좋다고 볼 수 없다",
    answer: true,
    explain: "외상 매출, 재고 증가 등으로 이익은 있지만 현금이 없는 '흑자도산'이 발생할 수 있어요 ⚠️",
  },
  {
    id: "q184",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "부채비율이 높은 기업은 금리 상승기에 이자 부담이 커진다",
    answer: true,
    explain: "변동금리 부채가 많으면 금리가 오를수록 이자 비용이 늘어 순이익이 줄어들어요 📈",
  },
  {
    id: "q185",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "재무제표 분석 시 단일 연도보다 여러 연도의 추세를 함께 살펴보는 것이 중요하다",
    answer: true,
    explain: "1년 데이터는 일회성 이벤트로 왜곡될 수 있어요. 3~5년 추세를 보면 실체가 더 잘 보여요 📅",
  },

  // ── 기타 중급 지표 q186-q200 ──────────────────
  {
    id: "q186",
    difficulty: 2,
    tag: "📉 기술적 분석 — 이동평균",
    q: "이동평균선(Moving Average, MA)은 일정 기간의 주가를 평균 내어 추세를 파악하는 지표다",
    answer: true,
    explain: "단기(20일), 중기(60일), 장기(200일) 등 다양한 기간으로 추세 방향을 판단해요 📊",
  },
  {
    id: "q187",
    difficulty: 2,
    tag: "📉 기술적 분석 — 이동평균",
    q: "200일 이동평균선은 장기 추세를 판단하는 대표적인 기준선으로 사용된다",
    answer: true,
    explain: "주가가 200일선 위에 있으면 장기 상승장, 아래에 있으면 장기 하락장으로 보는 경향이 있어요 📈",
  },
  {
    id: "q188",
    difficulty: 2,
    tag: "📉 기술적 분석 — 이동평균",
    q: "주가가 이동평균선 위에 있으면 상승 추세, 아래에 있으면 하락 추세로 판단하는 경향이 있다",
    answer: true,
    explain: "이동평균선이 지지선·저항선 역할을 하기도 해요. 절대적 기준은 아니에요 📊",
  },
  {
    id: "q189",
    difficulty: 2,
    tag: "📉 기술적 분석 — 볼린저밴드",
    q: "볼린저밴드(Bollinger Bands)는 이동평균선을 중심으로 표준편차를 이용해 상·하단 밴드를 그린 지표다",
    answer: true,
    explain: "중간(20일 MA), 상단(중간+2σ), 하단(중간-2σ)으로 구성돼요. 변동성을 시각화한 지표예요 📊",
  },
  {
    id: "q190",
    difficulty: 2,
    tag: "📉 기술적 분석 — 볼린저밴드",
    q: "볼린저밴드의 밴드 폭이 좁아지는 현상(Squeeze)은 향후 큰 변동성 확대를 예고하기도 한다",
    answer: true,
    explain: "밴드가 좁아질수록 에너지가 응축되는 상태예요. 이후 상하 어느 방향으로든 급등락할 가능성이 커요 ⚡",
  },
  {
    id: "q191",
    difficulty: 2,
    tag: "💹 밸류에이션 — PSR",
    q: "PSR(주가매출액비율)은 주가를 주당 매출액으로 나눈 값으로 적자 기업 평가에도 활용된다",
    answer: true,
    explain: "Price-to-Sales Ratio. 아직 이익이 없는 스타트업·성장주 평가에 유용해요 📊",
  },
  {
    id: "q192",
    difficulty: 2,
    tag: "💹 밸류에이션 — ROA",
    q: "ROA(총자산이익률) = 순이익 ÷ 총자산 × 100으로 계산한다",
    answer: true,
    explain: "Return on Assets. 기업이 보유한 전체 자산으로 얼마나 이익을 냈는지 보는 효율성 지표예요 📊",
  },
  {
    id: "q193",
    difficulty: 2,
    tag: "💹 밸류에이션 — ROA",
    q: "ROA가 높을수록 기업이 보유 자산을 더 효율적으로 활용하고 있다는 의미다",
    answer: true,
    explain: "같은 자산으로 더 많은 이익을 낸다면 더 우수한 경영을 하고 있는 것이에요 💪",
  },
  {
    id: "q194",
    difficulty: 2,
    tag: "📉 기술적 분석 — 거래량",
    q: "주가가 급등할 때 거래량도 함께 크게 늘어나면 그 상승의 신뢰도가 더 높다고 본다",
    answer: true,
    explain: "거래량은 추세의 신뢰도 지표예요. 거래량 없는 상승은 금방 꺼질 가능성이 높아요 📊",
  },
  {
    id: "q195",
    difficulty: 2,
    tag: "💹 밸류에이션 — PEG",
    q: "PEG 비율(PEG Ratio) = PER ÷ 이익성장률이며, 1 이하면 성장성 대비 저평가 신호로 볼 수 있다",
    answer: true,
    explain: "PER만으로 놓친 성장성을 보완하는 지표예요. PEG 1 = 성장률에 맞는 적정 가격이에요 🎯",
  },
  {
    id: "q196",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "영업레버리지(Operating Leverage)가 높은 기업은 매출 변화에 영업이익이 더 크게 반응한다",
    answer: true,
    explain: "고정비 비중이 높은 기업이 이에 해당해요. 매출이 오르면 이익이 폭발적으로 늘지만 반대도 마찬가지예요 ⚡",
  },
  {
    id: "q197",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "순이익률(Net Profit Margin) = 순이익 ÷ 매출액 × 100이다",
    answer: true,
    explain: "매출 100원 중 몇 원이 최종 이익으로 남는지를 보여줘요. 높을수록 수익성이 뛰어난 기업이에요 📊",
  },
  {
    id: "q198",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "잉여현금흐름(FCF: Free Cash Flow) = 영업활동 현금흐름 - 자본적 지출(CAPEX)이다",
    answer: true,
    explain: "본업에서 번 현금에서 사업 유지·확장을 위한 설비 투자를 뺀 진짜 자유 현금이에요 💰",
  },
  {
    id: "q199",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "잉여현금흐름(FCF)이 꾸준히 증가하는 기업은 배당 확대, 자사주 매입 등 주주환원이 가능하다",
    answer: true,
    explain: "FCF가 풍부해야 배당을 늘리거나 자사주를 살 여력이 생겨요. 주주환원의 원천이에요 💵",
  },
  {
    id: "q200",
    difficulty: 2,
    tag: "📋 재무제표",
    q: "기업 분석 시 재무제표 수치뿐 아니라 사업 모델, 경쟁 구도, 산업 트렌드도 함께 고려해야 한다",
    answer: true,
    explain: "숫자는 과거를 보여줘요. 미래 가치를 보려면 정성적 요소(경쟁력, 시장 변화)도 반드시 봐야 해요 🔍",
  },

  // ════════════════════════════════════════════════
  //  DIFFICULTY 3 — 고급 (Lv 8-10)
  // ════════════════════════════════════════════════

  {
    id: 301,
    difficulty: 3,
    tag: "📈 고급 금융",
    q: "PEG 비율(PEG Ratio)은 PER을 EPS 성장률로 나눈 값이다",
    answer: true,
    explain: "PEG = PER ÷ EPS 성장률. 성장성을 감안한 밸류에이션 지표예요. 1 이하면 저평가 신호로 봐요 📊",
  },
  {
    id: 302,
    difficulty: 3,
    tag: "📈 고급 금융",
    q: "현금흐름할인법(DCF)에서 할인율이 높아지면 기업의 내재 가치는 올라간다",
    answer: false,
    explain: "할인율↑ → 미래 현금흐름의 현재가치↓ → 기업 내재가치↓. 반비례 관계예요 📉",
  },
  {
    id: 303,
    difficulty: 3,
    tag: "📈 고급 금융",
    q: "EBITDA는 이자·세금·감가상각비 차감 전 이익을 의미한다",
    answer: true,
    explain: "Earnings Before Interest, Taxes, Depreciation and Amortization. 영업 현금창출력을 보는 지표예요 💰",
  },
  {
    id: 304,
    difficulty: 3,
    tag: "📈 고급 금융",
    q: "EV/EBITDA 비율이 낮을수록 기업이 저평가됐을 가능성이 높다",
    answer: true,
    explain: "EV(기업가치)를 EBITDA로 나눈 것. 값이 낮으면 그 현금흐름 대비 기업을 싸게 살 수 있다는 의미예요 📊",
  },
  {
    id: 305,
    difficulty: 3,
    tag: "📈 고급 금융",
    q: "알파(Alpha)는 시장 평균 대비 초과 달성한 수익률을 의미한다",
    answer: true,
    explain: "S&P500이 10% 올랐는데 내 포트폴리오가 15% 오르면 알파는 +5%예요. 펀드 매니저의 실력 지표예요 🎯",
  },
  {
    id: 306,
    difficulty: 3,
    tag: "📈 고급 금융",
    q: "베타(Beta) 값이 1.5인 주식은 시장 대비 변동성이 50% 더 크다",
    answer: true,
    explain: "베타 1.5 = 시장이 10% 오르면 15% 오르고, 10% 내리면 15% 내린다는 의미예요 ⚡",
  },
  {
    id: 307,
    difficulty: 3,
    tag: "📈 고급 금융",
    q: "샤프 지수(Sharpe Ratio)가 높을수록 위험 대비 수익 효율이 좋다",
    answer: true,
    explain: "샤프 비율 = (수익률 - 무위험수익률) ÷ 표준편차. 1 이상이면 양호, 2 이상이면 우수해요 📊",
  },
  {
    id: 308,
    difficulty: 3,
    tag: "📈 고급 금융",
    q: "무위험수익률(Risk-free rate)로는 주로 미국 10년 국채 수익률을 사용한다",
    answer: true,
    explain: "미국 국채는 사실상 디폴트 위험이 없다고 간주돼 투자 수익률 비교의 기준선으로 써요 🏛️",
  },
  {
    id: 309,
    difficulty: 3,
    tag: "📈 고급 금융",
    q: "리츠(REITs)는 수익의 70% 이상을 배당으로 지급해야 한다",
    answer: false,
    explain: "미국 리츠의 법적 요건은 과세 소득의 90% 이상을 배당으로 지급하는 것이에요 🏠",
  },
  {
    id: 310,
    difficulty: 3,
    tag: "📈 고급 금융",
    q: "역수익률 곡선(Inverted Yield Curve)은 역사적으로 경기침체의 선행 지표였다",
    answer: true,
    explain: "단기 금리가 장기 금리보다 높아지는 현상. 과거 8번의 침체 모두 이 신호가 먼저 나타났어요 📉",
  },
  {
    id: 311,
    difficulty: 3,
    tag: "🏦 거시경제",
    q: "양적완화(QE)는 중앙은행이 채권을 매입해 시중에 유동성을 공급하는 정책이다",
    answer: true,
    explain: "금리 인하 여지가 없을 때 쓰는 비전통적 통화정책이에요. 2008·2020년에 대규모로 시행됐어요 🏦",
  },
  {
    id: 312,
    difficulty: 3,
    tag: "🏦 거시경제",
    q: "테이퍼링(Tapering)은 중앙은행이 자산 매입 규모를 점진적으로 줄이는 것이다",
    answer: true,
    explain: "양적완화 종료 과정. 갑자기 멈추면 시장 충격이 크니 서서히 줄여가요 📊",
  },
  {
    id: 313,
    difficulty: 3,
    tag: "🏦 거시경제",
    q: "미국 연방준비제도(Fed)의 법적 책무는 물가 안정과 완전 고용 두 가지다",
    answer: true,
    explain: "이를 '이중 책무(Dual Mandate)'라고 해요. 유럽중앙은행(ECB)은 물가 안정만이 단일 목표예요 🏛️",
  },
  {
    id: 314,
    difficulty: 3,
    tag: "🏦 거시경제",
    q: "콘탱고(Contango) 시장에서는 선물 가격이 현물 가격보다 낮다",
    answer: false,
    explain: "콘탱고는 선물 가격 > 현물 가격인 상황이에요. 반대는 백워데이션(Backwardation)이에요 📈",
  },
  {
    id: 315,
    difficulty: 3,
    tag: "🏦 거시경제",
    q: "VIX 지수가 30 이상이면 시장 변동성이 매우 높은 공포 상태로 볼 수 있다",
    answer: true,
    explain: "VIX는 '공포 지수'라고도 불려요. 20 이하는 안정, 30 이상은 극도의 불안 상태를 의미해요 😱",
  },
  {
    id: 316,
    difficulty: 3,
    tag: "📈 고급 금융",
    q: "모멘텀 투자(Momentum Investing)는 최근 수익률이 좋은 자산을 매수하는 전략이다",
    answer: true,
    explain: "오르는 주식이 계속 오르는 경향을 이용하는 전략이에요. 추세추종 매매와 비슷해요 🚀",
  },
  {
    id: 317,
    difficulty: 3,
    tag: "📈 고급 금융",
    q: "블랙-숄즈 모형(Black-Scholes Model)은 주식 채권의 가격을 산정하는 공식이다",
    answer: false,
    explain: "블랙-숄즈는 옵션(Option) 가격 결정 모형이에요. 1997년 노벨 경제학상을 받은 이론이에요 📐",
  },
  {
    id: 318,
    difficulty: 3,
    tag: "📈 고급 금융",
    q: "헤지펀드(Hedge Fund)는 일반 개인 투자자도 자유롭게 가입할 수 있다",
    answer: false,
    explain: "보통 1억 달러 이상의 투자 요건이나 자격 있는 투자자(Accredited Investor) 조건이 있어요 🔒",
  },
  {
    id: 319,
    difficulty: 3,
    tag: "📈 고급 금융",
    q: "S&P500 지수 편입 조건 중 하나는 4분기 연속 흑자(GAAP 순이익) 기록이다",
    answer: true,
    explain: "시가총액·유동성 외에도 4분기 연속 순이익 흑자가 필수 요건이에요. 그래서 테슬라도 흑자 전환 후 편입됐어요 📊",
  },
  {
    id: 320,
    difficulty: 3,
    tag: "🏦 거시경제",
    q: "국제결제은행(BIS)이 권고하는 은행의 자기자본비율(BIS 비율) 최소 기준은 8%다",
    answer: true,
    explain: "바젤협약에 따른 기준이에요. 은행이 부실화되지 않도록 최소한의 자본을 보유하게 하는 규제예요 🏦",
  },
  {
    id: 321,
    difficulty: 3,
    tag: "📈 고급 금융",
    q: "자사주 매입(Share Buyback)은 주당순이익(EPS)을 높이는 효과가 있다",
    answer: true,
    explain: "발행주식 수가 줄어들면 동일한 순이익을 더 적은 주식이 나눠 가져 EPS가 올라가요 📈",
  },
  {
    id: 322,
    difficulty: 3,
    tag: "🏦 거시경제",
    q: "LIBOR(런던 은행 간 금리)는 2023년 SOFR로 완전히 대체되었다",
    answer: true,
    explain: "LIBOR 조작 스캔들 이후 2017년 폐지가 결정됐고, 2023년 6월 공식 종료됐어요 🏛️",
  },

  // ── 옵션 q201-q235 ────────────────────────────
  {
    id: "q201",
    difficulty: 3,
    tag: "🎯 옵션",
    q: "콜옵션(Call Option) 매수자는 기초자산을 행사가격에 살 수 있는 '권리'를 갖는다",
    answer: true,
    explain: "권리이지 의무가 아니에요. 불리하면 행사하지 않으면 그만이에요. 손실은 프리미엄으로 제한돼요 📋",
  },
  {
    id: "q202",
    difficulty: 3,
    tag: "🎯 옵션",
    q: "풋옵션(Put Option) 매수자는 기초자산을 행사가격에 팔 수 있는 '권리'를 갖는다",
    answer: true,
    explain: "주가 하락 시 이익이 나는 구조예요. 주식 하락 방어 수단(헤지)으로도 널리 활용돼요 📉",
  },
  {
    id: "q203",
    difficulty: 3,
    tag: "🎯 옵션",
    q: "옵션 매수자는 프리미엄을 지불했으므로 만기일에 반드시 옵션을 행사해야 한다",
    answer: false,
    explain: "옵션은 '권리'지 '의무'가 아니에요. 외가격(OTM) 상태면 행사하지 않고 포기하면 돼요 💡",
  },
  {
    id: "q204",
    difficulty: 3,
    tag: "🎯 옵션",
    q: "옵션 매도자(Writer)는 매수자가 행사권을 사용하면 반드시 이에 응할 의무가 있다",
    answer: true,
    explain: "매도자는 의무를 지는 대가로 프리미엄을 받아요. 리스크가 크기 때문에 증거금이 요구돼요 ⚠️",
  },
  {
    id: "q205",
    difficulty: 3,
    tag: "🎯 옵션",
    q: "행사가격(Strike Price)이란 옵션 계약에서 미리 합의된 매매 기준 가격이다",
    answer: true,
    explain: "콜옵션 매수자는 이 가격에 살 권리, 풋옵션 매수자는 이 가격에 팔 권리를 갖는 거예요 📊",
  },
  {
    id: "q206",
    difficulty: 3,
    tag: "🎯 옵션",
    q: "옵션 프리미엄은 내재가치(Intrinsic Value)와 시간가치(Time Value)의 합으로 구성된다",
    answer: true,
    explain: "프리미엄 = 내재가치 + 시간가치. 만기가 길수록, 변동성이 클수록 시간가치가 높아요 📊",
  },
  {
    id: "q207",
    difficulty: 3,
    tag: "🎯 옵션",
    q: "내가격(ITM: In-The-Money) 콜옵션은 기초자산 현재가가 행사가격보다 높은 상태다",
    answer: true,
    explain: "지금 당장 행사해도 이익이 나는 상태예요. 내재가치 = 기초자산 현재가 - 행사가격 > 0 📈",
  },
  {
    id: "q208",
    difficulty: 3,
    tag: "🎯 옵션",
    q: "외가격(OTM: Out-of-The-Money) 콜옵션의 내재가치(Intrinsic Value)는 0이다",
    answer: true,
    explain: "기초자산 현재가 < 행사가격이면 지금 행사해봤자 손해이므로 내재가치는 0이에요. 시간가치만 있어요 💡",
  },
  {
    id: "q209",
    difficulty: 3,
    tag: "🎯 옵션",
    q: "유럽형 옵션(European Option)은 만기일 당일에만 행사할 수 있다",
    answer: true,
    explain: "반면 미국형 옵션은 만기 이전 언제든 행사 가능해요. S&P500 옵션 등 지수 옵션은 주로 유럽형이에요 🌍",
  },
  {
    id: "q210",
    difficulty: 3,
    tag: "🎯 옵션",
    q: "미국형 옵션(American Option)은 만기일 이전에도 언제든지 행사할 수 있다",
    answer: true,
    explain: "조기 행사 가능성 때문에 같은 조건의 유럽형보다 프리미엄이 높거나 같아요 🇺🇸",
  },
  {
    id: "q211",
    difficulty: 3,
    tag: "🎯 옵션 — 그릭스",
    q: "델타(Delta)는 기초자산 가격이 1단위 변할 때 옵션 가격이 얼마나 변하는지를 나타낸다",
    answer: true,
    explain: "콜 델타는 0~1, 풋 델타는 -1~0 사이예요. 등가격(ATM) 옵션의 델타는 약 ±0.5예요 📊",
  },
  {
    id: "q212",
    difficulty: 3,
    tag: "🎯 옵션 — 그릭스",
    q: "감마(Gamma)는 기초자산 가격 변화에 따른 델타의 변화율이다",
    answer: true,
    explain: "감마가 클수록 델타가 빠르게 변해요. 등가격(ATM) 옵션 근방에서 가장 크고 만기 가까울수록 급증해요 ⚡",
  },
  {
    id: "q213",
    difficulty: 3,
    tag: "🎯 옵션 — 그릭스",
    q: "세타(Theta)는 시간이 하루 지날 때마다 옵션 가격이 감소하는 금액을 나타낸다",
    answer: true,
    explain: "'시간 가치 감소(Time Decay)'를 나타내요. 만기가 가까울수록 세타 손실이 가속화돼요 ⏳",
  },
  {
    id: "q214",
    difficulty: 3,
    tag: "🎯 옵션 — 그릭스",
    q: "베가(Vega)는 내재변동성(IV)이 1% 변할 때 옵션 가격의 변화량을 나타낸다",
    answer: true,
    explain: "IV가 높아지면 모든 옵션(콜·풋 모두) 프리미엄이 오르고, IV가 낮아지면 내려가요 📊",
  },
  {
    id: "q215",
    difficulty: 3,
    tag: "🎯 옵션 — 그릭스",
    q: "로(Rho)는 금리 변화가 옵션 가격에 미치는 영향을 나타내는 그릭스(Greeks) 지표다",
    answer: true,
    explain: "금리 상승 시 콜옵션 가격은 오르고 풋옵션 가격은 내리는 경향이 있어요. 단기 옵션에선 영향이 미미해요 🏦",
  },
  {
    id: "q216",
    difficulty: 3,
    tag: "🎯 옵션 — 그릭스",
    q: "옵션의 시간가치(Time Value)는 만기가 가까워질수록 빠르게 감소한다",
    answer: true,
    explain: "세타 감쇠(Theta Decay)는 만기 30일 이내부터 급격히 빨라져요. 매도자에겐 유리, 매수자에겐 불리해요 ⏱️",
  },
  {
    id: "q217",
    difficulty: 3,
    tag: "🎯 옵션",
    q: "내재변동성(IV)이 높아지면 콜옵션과 풋옵션 프리미엄이 모두 상승한다",
    answer: true,
    explain: "변동성이 커질수록 옵션이 이익을 낼 가능성도 커지기 때문에 모든 옵션의 가치가 높아져요 📈",
  },
  {
    id: "q218",
    difficulty: 3,
    tag: "🎯 옵션 — 전략",
    q: "커버드콜(Covered Call) 전략은 주식을 보유하면서 해당 주식의 콜옵션을 매도하는 전략이다",
    answer: true,
    explain: "상승 이익을 일부 포기하는 대신 프리미엄 수입을 얻어 보유 비용을 낮추는 보수적 전략이에요 📊",
  },
  {
    id: "q219",
    difficulty: 3,
    tag: "🎯 옵션 — 전략",
    q: "보호적 풋(Protective Put) 전략은 주식을 보유하면서 풋옵션을 매수해 하락 위험을 헤지하는 방법이다",
    answer: true,
    explain: "보험료(프리미엄) 내고 하락 손실에 상한선을 두는 전략이에요. 주식의 보험이라고 생각하면 돼요 🛡️",
  },
  {
    id: "q220",
    difficulty: 3,
    tag: "🎯 옵션 — 전략",
    q: "스트래들(Straddle) 매수는 동일 행사가격의 콜옵션과 풋옵션을 동시에 매수하는 전략이다",
    answer: true,
    explain: "큰 가격 변동이 예상될 때 방향에 상관없이 이익을 추구하는 전략이에요. 실적 발표·이벤트 전에 자주 써요 ⚡",
  },
  {
    id: "q221",
    difficulty: 3,
    tag: "🎯 옵션 — 전략",
    q: "스트래들 매수는 기초자산이 거의 변동 없이 횡보할 때 가장 수익이 높다",
    answer: false,
    explain: "횡보하면 두 옵션 모두 가치를 잃어 손실이 나요. 스트래들 매수는 큰 변동을 기대할 때 쓰는 전략이에요 ⚠️",
  },
  {
    id: "q222",
    difficulty: 3,
    tag: "🎯 옵션",
    q: "내재변동성(IV)이 역사적 변동성(HV)보다 현저히 낮을 때 옵션 매수가 상대적으로 유리할 수 있다",
    answer: true,
    explain: "옵션이 싸게 팔리는 상황이에요. 반대로 IV > HV이면 옵션이 비싸므로 매도 전략이 유리해요 💡",
  },
  {
    id: "q223",
    difficulty: 3,
    tag: "🎯 옵션",
    q: "콜옵션 매도자의 최대 이익은 수취한 프리미엄으로 제한된다",
    answer: true,
    explain: "매도자는 프리미엄 이상을 벌 수 없어요. 반면 기초자산이 무한정 오르면 손실도 무한정이에요 📊",
  },
  {
    id: "q224",
    difficulty: 3,
    tag: "🎯 옵션",
    q: "나체 콜옵션(Naked Call) 매도자는 기초자산 가격이 무한정 오르면 이론적으로 무한한 손실에 노출된다",
    answer: true,
    explain: "보유 주식 없이 콜옵션을 파는 전략이에요. 가장 위험한 포지션 중 하나로 증거금 요건이 매우 높아요 ⚠️",
  },
  {
    id: "q225",
    difficulty: 3,
    tag: "🎯 옵션",
    q: "풋옵션 매수자의 이론적 최대 이익은 기초자산 가격이 0이 될 때의 내재가치로 제한된다",
    answer: true,
    explain: "주가가 0 아래로 내려갈 수는 없으므로 최대이익 = 행사가격 - 프리미엄. 무한대가 아니에요 📉",
  },
  {
    id: "q226",
    difficulty: 3,
    tag: "🎯 옵션",
    q: "블랙-숄즈 모형의 5대 입력 변수는 기초자산 현재가, 행사가격, 무위험이자율, 잔존만기, 변동성이다",
    answer: true,
    explain: "이 5가지 변수로 유럽형 콜·풋옵션의 이론 가격을 계산해요. 1997년 노벨 경제학상 수상 이론이에요 🏆",
  },
  {
    id: "q227",
    difficulty: 3,
    tag: "🎯 옵션",
    q: "VIX 지수는 S&P500 옵션의 내재변동성을 기반으로 산출된다",
    answer: true,
    explain: "향후 30일 S&P500의 예상 변동성을 연율화한 지수예요. 시장 공포가 클수록 VIX가 높아져요 😱",
  },
  {
    id: "q228",
    difficulty: 3,
    tag: "🎯 옵션",
    q: "풋-콜 패리티(Put-Call Parity)는 동일 조건의 유럽형 풋옵션과 콜옵션 가격 간에 성립하는 등가 관계다",
    answer: true,
    explain: "C - P = S - PV(K). 이 관계가 깨지면 차익거래 기회가 생겨 즉시 시장이 균형을 회복해요 ⚖️",
  },
  {
    id: "q229",
    difficulty: 3,
    tag: "🎯 옵션 — 전략",
    q: "버티컬 스프레드(Vertical Spread)는 만기는 같고 행사가격이 다른 옵션을 동시에 사고파는 전략이다",
    answer: true,
    explain: "최대 이익과 손실이 미리 정해진 제한적 리스크 전략이에요. 불 스프레드와 베어 스프레드가 대표적이에요 📊",
  },
  {
    id: "q230",
    difficulty: 3,
    tag: "🎯 옵션 — 전략",
    q: "아이언 콘도르(Iron Condor)는 4개의 행사가격을 사용하는 중립형 복합 옵션 전략이다",
    answer: true,
    explain: "기초자산이 일정 범위 내에서 움직일 때 수익이 나는 전략이에요. 변동성이 낮을 것으로 예상할 때 써요 🦅",
  },
  {
    id: "q231",
    difficulty: 3,
    tag: "🎯 옵션 — 그릭스",
    q: "등가격(ATM) 옵션은 내가격(ITM)이나 외가격(OTM) 옵션보다 감마(Gamma) 값이 가장 크다",
    answer: true,
    explain: "ATM에서 작은 주가 변화로도 ITM/OTM이 바뀔 수 있어 델타 변화가 가장 민감하게 일어나요 ⚡",
  },
  {
    id: "q232",
    difficulty: 3,
    tag: "🎯 옵션",
    q: "옵션의 내재가치(Intrinsic Value)는 음수(-)가 될 수 없다",
    answer: true,
    explain: "OTM이면 내재가치=0, ITM이면 양수예요. 음수가 되면 행사 안 하면 그만이므로 최솟값은 0이에요 💡",
  },
  {
    id: "q233",
    difficulty: 3,
    tag: "🎯 옵션",
    q: "볼록성(Convexity) 효과로 인해 옵션 가격은 기초자산 가격 변화에 대해 비선형적으로 반응한다",
    answer: true,
    explain: "이것이 감마가 존재하는 이유예요. 선형 근사(델타만)로는 설명 못하는 곡선적 가격 변화가 생겨요 📊",
  },
  {
    id: "q234",
    difficulty: 3,
    tag: "🎯 옵션",
    q: "변동성 스마일(Volatility Smile)이란 행사가격에 따라 내재변동성이 다르게 나타나는 현상이다",
    answer: true,
    explain: "블랙-숄즈가 가정한 균일 변동성과 달리 실제 시장에선 ITM/OTM의 IV가 ATM보다 높은 패턴이 나타나요 📊",
  },
  {
    id: "q235",
    difficulty: 3,
    tag: "🎯 옵션",
    q: "변동성 스큐(Volatility Skew)에서 주식 옵션은 일반적으로 하락 방향의 풋옵션 IV가 더 높게 나타난다",
    answer: true,
    explain: "투자자들이 하락 헤지를 위해 OTM 풋을 더 많이 사기 때문이에요. '스마일'보다 한쪽이 비대칭적이에요 📉",
  },

  // ── 채권 q236-q265 ────────────────────────────
  {
    id: "q236",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "채권(Bond)은 발행자가 만기에 원금을 상환하고 보유 기간 동안 정기적으로 이자(쿠폰)를 지급하는 채무 증서다",
    answer: true,
    explain: "정부·기업이 자금을 빌리기 위해 발행해요. 주식과 달리 이자와 원금 상환 의무가 있어요 📄",
  },
  {
    id: "q237",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "고정금리 채권(Fixed-Rate Bond)의 표면이율(Coupon Rate)은 발행 시 결정되어 만기까지 변하지 않는다",
    answer: true,
    explain: "시장금리가 올라도 이미 약속된 쿠폰은 그대로예요. 단, 변동금리채(FRN)는 시장금리에 연동돼요 📊",
  },
  {
    id: "q238",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "표면이율이 같다면 만기가 긴 채권이 금리 변동에 따른 가격 변동이 더 크다",
    answer: true,
    explain: "잔존 현금흐름 기간이 길수록 금리 영향을 더 오래 받기 때문이에요. 이를 듀레이션 개념으로 설명해요 📈",
  },
  {
    id: "q239",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "듀레이션(Duration)은 채권에 투자한 자금의 평균 회수 기간이자 금리 민감도를 나타내는 지표다",
    answer: true,
    explain: "듀레이션이 길수록 금리 변동에 민감해요. 제로쿠폰채의 듀레이션 = 만기, 쿠폰채는 만기보다 짧아요 📊",
  },
  {
    id: "q240",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "수정 듀레이션(Modified Duration)이 7인 채권은 금리가 1% 상승할 때 가격이 약 7% 하락한다",
    answer: true,
    explain: "수정 듀레이션 = 맥컬레이 듀레이션 ÷ (1 + YTM). 금리 민감도의 퍼센트 근사치를 계산해요 📉",
  },
  {
    id: "q241",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "채권의 볼록성(Convexity)으로 인해 금리 하락 시 가격 상승폭이 듀레이션 예측보다 더 크다",
    answer: true,
    explain: "가격-금리 관계가 직선이 아닌 볼록한 곡선이에요. 볼록성이 클수록 투자자에게 유리한 비대칭성이 생겨요 📊",
  },
  {
    id: "q242",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "신용등급 AAA 채권은 일반적으로 BB 등급 채권보다 수익률(금리)이 낮다",
    answer: true,
    explain: "신용 위험이 낮을수록 투자자가 요구하는 위험 프리미엄이 작아 금리도 낮아요 🏆",
  },
  {
    id: "q243",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "정크본드(Junk Bond)는 S&P 기준 BB+ 이하의 투기등급(Non-Investment Grade) 채권이다",
    answer: true,
    explain: "하이일드 채권이라고도 불러요. 부도 위험이 높지만 그만큼 높은 수익률을 제공해요 ⚠️",
  },
  {
    id: "q244",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "제로쿠폰채권(Zero-Coupon Bond)은 정기 이자 없이 액면가보다 낮은 가격으로 발행되어 만기에 액면가로 상환된다",
    answer: true,
    explain: "미국 T-Bill이 대표적이에요. 할인 발행가와 액면가의 차이가 곧 투자 수익이에요 💰",
  },
  {
    id: "q245",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "정상적인 수익률 곡선(Yield Curve)은 장기채 수익률이 단기채보다 높은 우상향 형태다",
    answer: true,
    explain: "장기 투자의 불확실성에 대한 보상(기간 프리미엄)이 더 높기 때문이에요 📈",
  },
  {
    id: "q246",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "역수익률 곡선(Inverted Yield Curve)에서는 단기채 수익률이 장기채 수익률보다 높다",
    answer: true,
    explain: "경기침체 기대로 시장이 미래 금리 하락을 선반영할 때 발생해요. 역사적으로 경기침체 전에 나타났어요 📉",
  },
  {
    id: "q247",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "YTM(만기수익률)은 채권을 현재 가격으로 매수해 만기까지 보유했을 때의 연간 총수익률이다",
    answer: true,
    explain: "쿠폰 재투자 수익까지 포함한 개념이에요. 채권 투자 수익률을 비교할 때 가장 많이 쓰는 지표예요 📊",
  },
  {
    id: "q248",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "크레딧 스프레드(Credit Spread)란 기업채 수익률과 동일 만기 국채 수익률의 차이다",
    answer: true,
    explain: "신용 위험에 대한 추가 보상이에요. 스프레드가 확대되면 시장이 해당 기업의 위험을 더 크게 본다는 신호예요 📊",
  },
  {
    id: "q249",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "크레딧 스프레드가 확대(Widening)되면 해당 발행자의 신용 위험이 높아졌다는 의미다",
    answer: true,
    explain: "경기 침체기에 하이일드 채권 스프레드가 크게 벌어지는 것이 대표적인 예예요 ⚠️",
  },
  {
    id: "q250",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "TIPS(물가연동국채)는 원금이 CPI에 연동되어 조정되므로 인플레이션 헤지 수단으로 사용된다",
    answer: true,
    explain: "Treasury Inflation-Protected Securities. 물가가 오를수록 원금과 이자 지급액도 늘어나요 🛡️",
  },
  {
    id: "q251",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "하이일드(High-Yield) 채권은 투자등급 채권보다 이자율이 낮다",
    answer: false,
    explain: "높은 부도 위험에 대한 보상으로 수익률이 더 높아요. 위험·수익률은 비례해요 📈",
  },
  {
    id: "q252",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "채권의 시장 가격은 시장금리 변화에 따라 액면가(Par Value)와 달라질 수 있다",
    answer: true,
    explain: "금리 상승 → 기존 채권 가격 하락(할인 거래), 금리 하락 → 기존 채권 가격 상승(프리미엄 거래)해요 💹",
  },
  {
    id: "q253",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "콜러블 채권(Callable Bond)은 발행자가 만기 이전에 조기 상환(Call)할 수 있는 권리를 갖는다",
    answer: true,
    explain: "금리 하락 시 발행자가 이를 행사해 더 낮은 금리로 재발행해요. 투자자는 재투자 위험에 노출돼요 ⚠️",
  },
  {
    id: "q254",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "변동금리채(Floating Rate Bond)의 쿠폰은 SOFR 같은 기준금리에 연동해 변동된다",
    answer: true,
    explain: "금리 상승기에 쿠폰이 함께 오르기 때문에 고정금리채보다 가격 변동성이 낮아요 📊",
  },
  {
    id: "q255",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "채권 신용등급 평가 3대 기관은 Moody's, S&P Global Ratings, Fitch Ratings이다",
    answer: true,
    explain: "이 세 기관의 등급은 기관투자자의 투자 가능 여부를 결정하는 핵심 기준이 돼요 🏛️",
  },
  {
    id: "q256",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "S&P 기준 BBB- 이상이 투자등급(Investment Grade)이고, BB+ 이하가 투기등급(Speculative Grade)이다",
    answer: true,
    explain: "많은 기관투자자(연기금, 보험사)가 규정상 투자등급 채권만 보유할 수 있어 이 기준이 중요해요 📊",
  },
  {
    id: "q257",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "YTM이 표면이율보다 높으면 해당 채권이 현재 액면가보다 낮은 가격(할인)으로 거래되고 있다는 의미다",
    answer: true,
    explain: "시장금리 상승 → 기존 채권 매력 감소 → 가격 하락 → YTM 상승. 반비례 관계예요 📉",
  },
  {
    id: "q258",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "채권에 투자하면 주식과 달리 원금 손실이 절대 발생하지 않는다",
    answer: false,
    explain: "발행자 파산 시 원금 손실이 발생할 수 있고, 금리 상승 시 시장 가격도 하락해요 ⚠️",
  },
  {
    id: "q259",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "채권 사다리(Bond Ladder) 전략은 만기가 서로 다른 채권을 분산 보유해 재투자 및 금리 위험을 관리하는 방법이다",
    answer: true,
    explain: "채권이 차례로 만기되면 그때의 금리 수준으로 재투자할 수 있어 금리 변동 리스크를 분산해요 📊",
  },
  {
    id: "q260",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "미국 단기 국채(T-Bill)의 만기는 통상 4주·13주·26주·52주 등 1년 이하다",
    answer: true,
    explain: "2년 이상은 T-Note, 10년 초과는 T-Bond예요. T-Bill은 무위험 단기 운용 수단으로 활용돼요 🏛️",
  },
  {
    id: "q261",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "신흥국(Emerging Market) 채권은 신용 위험과 환율 위험이 복합적으로 작용해 선진국 채권보다 수익률이 높다",
    answer: true,
    explain: "고수익 이면엔 국가 부도, 통화 절하, 정치 리스크가 있어요. 적절한 분산투자가 필요해요 🌍",
  },
  {
    id: "q262",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "채권의 볼록성(Convexity)이 클수록 금리 하락 시 가격 상승 폭이 듀레이션 추정치보다 더 크다",
    answer: true,
    explain: "볼록성은 투자자에게 유리한 방향으로 작용해요. 금리 하락 시 이익은 예측보다 크고, 상승 시 손실은 예측보다 작아요 📈",
  },
  {
    id: "q263",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "채권 ETF는 금리 상승기에도 시장 가격이 하락하지 않는다",
    answer: false,
    explain: "채권 ETF는 구성 채권의 시장가격을 반영하므로 금리 상승 시 가격이 하락해요. '안전하다'는 오해를 주의해야 해요 ⚠️",
  },
  {
    id: "q264",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "스프레드 듀레이션(Spread Duration)은 크레딧 스프레드 변화에 따른 채권 가격 민감도를 나타낸다",
    answer: true,
    explain: "금리 듀레이션과 별도로, 신용 스프레드 확대·축소에 의한 가격 변동을 측정하는 지표예요 📊",
  },
  {
    id: "q265",
    difficulty: 3,
    tag: "🏛️ 채권",
    q: "쿠폰이 높은 채권은 쿠폰이 낮은 채권보다 듀레이션이 짧다",
    answer: true,
    explain: "쿠폰이 높을수록 초기에 더 많은 현금흐름이 회수되어 가중 평균 회수 기간(듀레이션)이 짧아져요 📊",
  },

  // ── 매크로 q266-q300 ──────────────────────────
  {
    id: "q266",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "명목 GDP 성장률에서 GDP 디플레이터를 제거하면 실질 GDP 성장률을 구할 수 있다",
    answer: true,
    explain: "실질 GDP = 명목 GDP ÷ GDP 디플레이터 × 100. 물가 상승 효과를 걷어낸 진짜 성장률이에요 📊",
  },
  {
    id: "q267",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "미국 경제에서 GDP가 2분기 연속 마이너스 성장하면 기술적 경기침체(Technical Recession)로 정의된다",
    answer: true,
    explain: "공식 경기침체 판정은 NBER이 고용·소비 등 다양한 지표를 종합해 판단해요. 2분기 규칙은 실용적 기준이에요 📉",
  },
  {
    id: "q268",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "연준(Fed)의 기준금리 인상은 소비·투자 위축을 통해 인플레이션을 억제하는 효과가 있다",
    answer: true,
    explain: "금리 상승 → 차입 비용↑ → 소비·투자↓ → 수요 감소 → 물가 하락 압력. 수요 측 인플레이션에 효과적이에요 📊",
  },
  {
    id: "q269",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "재정정책의 자동안정화 장치(Automatic Stabilizer)는 경기 침체 시 자동으로 정부 지출이 늘고 세수가 줄어 경기를 완충한다",
    answer: true,
    explain: "실업급여 증가·세수 감소 등이 자동으로 작동해 별도 정책 결정 없이도 경기 충격을 흡수해요 🛡️",
  },
  {
    id: "q270",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "연준(Fed)의 독립성이란 행정부·의회의 직접적 간섭 없이 통화정책을 자율적으로 결정할 수 있는 구조를 말한다",
    answer: true,
    explain: "단기 정치 논리가 장기 물가 안정 정책에 개입하지 못하도록 제도적으로 보호돼 있어요 🏛️",
  },
  {
    id: "q271",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "연준의 공개시장조작(OMO)은 국채를 매입·매각해 은행 시스템의 지급준비금을 조절하는 방법이다",
    answer: true,
    explain: "국채 매입 → 지급준비금 증가 → 금리 하락 압력, 국채 매각 → 지급준비금 감소 → 금리 상승 압력이에요 📊",
  },
  {
    id: "q272",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "연준 FOMC(연방공개시장위원회)는 연 8회 정기 회의를 통해 기준금리(FFR) 목표 범위를 결정한다",
    answer: true,
    explain: "6~7주 간격으로 열려요. 긴급 시 임시 회의도 소집할 수 있어요. 결과는 전 세계 시장에 즉각 영향을 줘요 📅",
  },
  {
    id: "q273",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "연준은 인플레이션 척도로 CPI보다 핵심 PCE(Core PCE) 지수를 더 중요하게 참고한다",
    answer: true,
    explain: "PCE는 소비자 행동 변화를 더 잘 반영하고, 코어(Core)는 식품·에너지 제외 기저 인플레이션을 봐요 📊",
  },
  {
    id: "q274",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "필립스 곡선(Phillips Curve)은 실업률과 인플레이션 사이의 역의 관계를 나타내는 이론이다",
    answer: true,
    explain: "고용 과열 → 임금·물가 상승, 실업 증가 → 물가 하락. 1970년 스태그플레이션으로 이 관계가 붕괴하기도 했어요 📊",
  },
  {
    id: "q275",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "스태그플레이션(Stagflation)은 경기침체와 고인플레이션이 동시에 발생하는 상황으로 중앙은행이 대응하기 가장 어렵다",
    answer: true,
    explain: "금리를 올리면 침체가 악화되고, 내리면 물가가 더 오르는 딜레마에 빠져요. 1970년대 오일쇼크 시기가 대표적이에요 😱",
  },
  {
    id: "q276",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "달러 인덱스(DXY)는 유로·엔·파운드·캐나다달러·스웨덴크로나·스위스프랑 6개 통화 대비 달러 가치를 측정한다",
    answer: true,
    explain: "6개 통화 중 유로 비중이 약 57.6%로 가장 높아요. 달러 강·약세 판단의 기준선이에요 💱",
  },
  {
    id: "q277",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "원유·금 같은 달러 표시 원자재는 일반적으로 달러 강세 시 가격이 하락하는 경향이 있다",
    answer: true,
    explain: "달러 강세 → 타국 통화로 환산 시 원자재가 비싸짐 → 수요 감소 → 가격 하락. 역의 상관관계예요 📉",
  },
  {
    id: "q278",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "미국 10년물 국채 수익률은 모기지 금리, 기업 대출 금리 등 민간 시장금리의 기준점 역할을 한다",
    answer: true,
    explain: "무위험 장기 금리의 대표 지표예요. 10년물이 오르면 대출 금리도 연쇄적으로 높아지는 경향이 있어요 🏦",
  },
  {
    id: "q279",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "PMI(구매관리자지수)가 50 이상이면 해당 업종이 확장 국면, 50 미만이면 수축 국면임을 나타낸다",
    answer: true,
    explain: "기업 구매담당자 설문 기반 선행 지표예요. 실제 GDP보다 빠르게 경기 방향을 시사해줘요 📊",
  },
  {
    id: "q280",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "연준이 보유 자산을 축소하여 시중 유동성을 흡수하는 정책을 양적긴축(QT: Quantitative Tightening)이라 한다",
    answer: true,
    explain: "QE(자산 매입 확대)의 반대 과정이에요. 보유 국채를 만기 상환 후 재투자하지 않는 방식으로 진행해요 📉",
  },
  {
    id: "q281",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "M2 통화량은 현금, 요구불예금, 저축성 예금, 소액 정기예금 등을 포함하는 광의 통화 지표다",
    answer: true,
    explain: "M1(현금+요구불예금)보다 넓은 개념이에요. M2 증가율이 인플레이션 압력의 선행 지표로 활용돼요 📊",
  },
  {
    id: "q282",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "전 세계 외환보유고에서 미국 달러(USD)가 차지하는 비중이 가장 크다",
    answer: true,
    explain: "약 60% 내외를 달러가 차지하고 유로가 2위예요. 달러의 기축통화 지위를 보여주는 지표예요 💵",
  },
  {
    id: "q283",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "연준이 기준금리를 인상하면 신흥국 통화 가치가 하락하고 자본이 유출되는 경향이 있다",
    answer: true,
    explain: "달러 강세 → 달러 표시 부채 상환 부담↑, 달러 수익률↑ → 신흥국에서 자금이 빠져나가요 📉",
  },
  {
    id: "q284",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "연준의 FOMC 점도표(Dot Plot)는 위원들의 향후 기준금리 전망을 점으로 시각화한 차트다",
    answer: true,
    explain: "각 위원이 익명으로 연말 금리 예상치를 제출해요. 시장의 금리 경로 예측에 중요한 힌트를 제공해요 🎯",
  },
  {
    id: "q285",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "연준을 포함한 주요국 중앙은행은 통상 연간 2%를 인플레이션 목표치로 설정한다",
    answer: true,
    explain: "2%는 너무 낮지도 높지도 않은 경제 활력을 유지할 수 있는 수준으로 경험적으로 채택됐어요 🎯",
  },
  {
    id: "q286",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "일본은행(BOJ)의 YCC(수익률 곡선 제어) 정책은 10년 만기 국채 금리를 목표 범위 내로 유지하기 위해 무제한 채권을 매입하는 방식이다",
    answer: true,
    explain: "디플레이션 탈피를 위해 도입됐어요. 2024년 이후 BOJ가 이 정책을 단계적으로 해제하면서 엔화 변동성이 커졌어요 🇯🇵",
  },
  {
    id: "q287",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "달러 강세는 미국 수입품 가격을 낮춰 미국 내 인플레이션을 억제하는 효과가 있다",
    answer: true,
    explain: "달러 강세 → 수입품이 상대적으로 저렴해짐 → 수입 물가 하락 → CPI 하락 압력이에요 📉",
  },
  {
    id: "q288",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "테이퍼 텐트럼(Taper Tantrum)은 연준의 양적완화 축소 신호에 채권시장이 과민 반응해 금리가 급등한 현상이다",
    answer: true,
    explain: "2013년 버냉키 의장의 테이퍼링 언급 후 10년물 금리가 급등했어요. 소통의 중요성을 보여준 사례예요 📈",
  },
  {
    id: "q289",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "경상수지 흑자란 한 나라가 대외 재화·서비스·소득 거래에서 벌어들이는 외화가 지출하는 외화보다 많은 상태다",
    answer: true,
    explain: "한국의 경상수지 흑자는 수출 경쟁력을 나타내요. 지나친 흑자는 교역 상대국과 마찰을 일으키기도 해요 📊",
  },
  {
    id: "q290",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "재정승수(Fiscal Multiplier)란 정부 지출이 1달러 늘어날 때 최종적으로 GDP가 얼마나 증가하는지를 나타내는 배율이다",
    answer: true,
    explain: "승수 효과 덕분에 1달러 지출이 소비·투자로 이어지며 GDP를 1달러 이상 증가시키기도 해요 📊",
  },
  {
    id: "q291",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "국제통화기금(IMF)은 국제 무역 분쟁을 해결하기 위해 설립된 기관이다",
    answer: false,
    explain: "IMF는 국제 통화 협력과 금융 안정을 위해 설립됐어요. 무역 분쟁 해결은 WTO의 역할이에요 🌐",
  },
  {
    id: "q292",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "통화 스왑(Currency Swap) 협정은 두 국가가 서로 자국 통화를 미리 약속된 환율로 교환하는 협약이다",
    answer: true,
    explain: "외환위기 시 달러 유동성이 부족한 국가에 달러를 공급하는 안전망 역할을 해요. 한미 통화 스왑이 대표적이에요 🤝",
  },
  {
    id: "q293",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "연준이 기준금리를 인상하면 주택담보대출(모기지) 금리도 올라 부동산 수요에 하방 압력이 생긴다",
    answer: true,
    explain: "30년 고정 모기지 금리는 10년 국채 금리와 연동돼요. 기준금리 인상 사이클에서 부동산 시장이 위축되는 경향이 있어요 🏠",
  },
  {
    id: "q294",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "경기선행지수(LEI: Leading Economic Indicators)는 향후 3~6개월의 경기 방향을 예측하는 복합 지수다",
    answer: true,
    explain: "주간 실업수당 청구, 제조업 수주, 주가 등이 구성 요소예요. LEI 연속 하락은 경기침체 전조로 봐요 📊",
  },
  {
    id: "q295",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "GDP 디플레이터는 '명목 GDP ÷ 실질 GDP × 100'으로 경제 전반의 물가 수준을 측정하는 지표다",
    answer: true,
    explain: "CPI가 고정 바구니 기준인 반면, GDP 디플레이터는 경제 전체 산출물의 물가를 반영해요 📊",
  },
  {
    id: "q296",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "연준이 50bp(0.5%) 금리를 한 번에 인하하는 '빅컷(Big Cut)'은 경기 침체 우려가 크다는 신호로 해석되기도 한다",
    answer: true,
    explain: "통상 25bp씩 조정하는데 50bp를 한 번에 내리면 경기 긴급 처방으로 시장이 위기 신호로 받아들이기도 해요 ⚠️",
  },
  {
    id: "q297",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "경기침체기에는 보통 정부 세수가 줄고 사회보장 지출이 자동으로 늘어 재정 적자가 확대되는 경향이 있다",
    answer: true,
    explain: "이것이 자동안정화 장치예요. 정부 의도 없이도 재정이 자동으로 경기 완충 역할을 해요 💊",
  },
  {
    id: "q298",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "콜 자금 금리(Overnight Rate)는 은행 간 하루짜리 단기 자금 거래에 적용되는 금리로, 연준의 기준금리와 가장 밀접하게 연동된다",
    answer: true,
    explain: "미국의 EFFR(유효연방기금금리)이 대표적이에요. 연준의 정책금리가 목표 범위를 유지하도록 OMO로 조절해요 🏦",
  },
  {
    id: "q299",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "긴축 재정(Austerity)은 정부 지출을 줄이고 세금을 올려 재정 적자를 감축하는 정책으로 단기적으로 경기에 부담이 될 수 있다",
    answer: true,
    explain: "2010년대 그리스·스페인 등 유럽 국가들이 채권단 요구로 시행해 경기침체를 심화시킨 사례가 있어요 📉",
  },
  {
    id: "q300",
    difficulty: 3,
    tag: "🌐 매크로",
    q: "스왑션(Swaption)은 미래에 이자율 스왑 계약을 체결할 수 있는 권리를 부여하는 파생상품이다",
    answer: true,
    explain: "금리 방향 베팅 또는 금리 리스크 헤지에 활용해요. 옵션(권리)과 스왑(계약)이 결합된 복합 파생상품이에요 📊",
  },
];
